Repository apify/apify-docs, pull requests merged in 2021-03, with the labels that each got.

#200 Use Ubuntu 20.04
  .github/workflows/build.yml
Labels: adhoc

#201 Update ubuntu version and region
  .github/workflows/close.yml
Labels: debt

#204 Improve info about actors from gist and zip
  docs/actors/development/source_code.md
Labels: adhoc, debt

#205 Feature: Updated run ressurect
  docs/api_v2/api_v2_reference.apib
  docs/webhooks/events.md
Labels: documentation

#211 Improve docs based on feedback
  docs/proxy/connection_settings.md
  docs/tutorials/log_into_a_website_using_puppeteer.md
Labels: adhoc, documentation, enhancement

#212 Improve titles and description for SEO
  docs/actors/development/state_persistence.md
  docs/tutorials/cache_data_to_improve_performance.md
  docs/tutorials/crawl_urls_from_a_google_sheet.md
  docs/tutorials/scrape_paginated_sites.md
Labels: adhoc, debt, documentation

#213 Update key-val docs
  docs/storage/key_value_store.md
Labels: debt, documentation, enhancement

#214 Remove broken Page Analyzer link from Web Scraping Techniques
  docs/web_scraping_101/web_scraping_techniques.md
Labels: bug

#210 Add the Memory and CPU article
  docs/actors/examples.md
  docs/actors/images/memory-cpu-usage-spike.png
  docs/actors/images/memory-settings.png
  docs/actors/limits.md
  docs/actors/memory_and_cpu.md
  docs/actors/publishing.md
  docs/actors/security.md
Labels: documentation, enhancement

#218 Add the "Compute units and consumption" article
  docs/actors/images/actor-usage.png
  docs/actors/running/compute_units.md
  docs/actors/running/input.md
  docs/actors/running/memory_and_cpu.md
Labels: documentation, enhancement
