Repository apify/apify-docs, pull requests merged in 2021-11, with the labels that each got.

#284 Fix lint, update packages, add package-lock, update to Node 14
  .eslintrc
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  .nvmrc
  docs/web_scraping_101/web_scraping_techniques.md
  docs/webhooks/actions.md
  package-lock.json
  package.json
  src/build.js
  src/parser.js
  src/webp_converter.js
Labels: bug, adhoc

#272 Add tutorials for scraping and processing data in Python
  docs/actors/development/base_docker_images.md
  docs/homepage_content.json
  docs/tutorials.md
  docs/tutorials/images/bbc-time-offset.png
  docs/tutorials/images/bbc-time-offset.webp
  docs/tutorials/images/bbc-weather-after-midnight.png
  docs/tutorials/images/bbc-weather-after-midnight.webp
  docs/tutorials/images/bbc-weather-devtools.png
  docs/tutorials/images/bbc-weather-devtools.webp
  docs/tutorials/images/bbc-weather-parser-source.png
  docs/tutorials/images/bbc-weather-parser-source.webp
  docs/tutorials/images/bbc-weather-prediction.png
  docs/tutorials/images/bbc-weather-prediction.webp
  docs/tutorials/images/bbc-weather-scraper-source.png
  docs/tutorials/images/bbc-weather-scraper-source.webp
  docs/tutorials/images/bbc-weather-url-format.png
  docs/tutorials/images/bbc-weather-url-format.webp
  docs/tutorials/process_data_using_python.md
  docs/tutorials/scrape_data_using_python.md
  examples/python-data-parser/main.py
  examples/python-data-parser/requirements.txt
  examples/python-data-scraper/main.py
  examples/python-data-scraper/requirements.txt
Labels: documentation, enhancement, medium priority

#285 Update homepage cards items
  docs/homepage_content.json
Labels: adhoc

#301 Move academy files
  docs/academy.md
  docs/fde.md
  docs/fde/browser_devtools.md
  docs/fde/computer_preparation.md
  docs/fde/extracting_data_with_devtools_part_1.md
  docs/fde/extracting_data_with_devtools_part_2.md
  docs/fde/extracting_data_with_node_part_1.md
  docs/fde/extracting_data_with_node_part_2.md
  docs/fde/images/basic-console-commands.png
  docs/fde/images/basic-console-commands.webp
  docs/fde/images/browser-devtools.png
  docs/fde/images/browser-devtools.webp
  docs/fde/images/data-in-excel.png
  docs/fde/images/data-in-excel.webp
  docs/fde/images/find-child-elements.png
  docs/fde/images/find-child-elements.webp
  docs/fde/images/hover-effect.png
  docs/fde/images/hover-effect.webp
  docs/fde/images/list-child-elements.png
  docs/fde/images/list-child-elements.webp
  docs/fde/images/print-all-websites-data.png
  docs/fde/images/print-all-websites-data.webp
  docs/fde/images/print-all-websites-text.png
  docs/fde/images/print-all-websites-text.webp
  docs/fde/images/print-all-websites.png
  docs/fde/images/print-all-websites.webp
  docs/fde/images/print-text-content.png
  docs/fde/images/print-text-content.webp
  docs/fde/images/print-website-data.png
  docs/fde/images/print-website-data.webp
  docs/fde/images/query-selector.png
  docs/fde/images/query-selector.webp
  docs/fde/images/selecting-container-element.png
  docs/fde/images/selecting-container-element.webp
  docs/fde/images/selecting-first-website.png
  docs/fde/images/selecting-first-website.webp
  docs/fde/images/terminal-all-websites-data.png
  docs/fde/images/terminal-all-websites-data.webp
  docs/fde/images/terminal-csv.png
  docs/fde/images/terminal-csv.webp
  docs/fde/project_setup.md
  docs/fde/save_to_csv.md
  docs/images/beginners-data-extraction.png
  docs/images/beginners-data-extraction.webp
  docs/web_scraping_for_beginners.md
Labels: adhoc
