Repository apify/apify-docs, pull requests merged in 2021-08, with the labels that each got.

#266 Fix get run endpoint link URL
  docs/api_v2/api_v2_reference.apib
Labels: bug

#265 Add references to the Python client & Python examples to various places
  README.md
  docs/actors/development/base_docker_images.md
  docs/actors/development/environment_variables.md
  docs/actors/development/input_schema.md
  docs/actors/development/source_code.md
  docs/actors/paid_actors.md
  docs/actors/running.md
  docs/api_v2/api_v2_reference.apib
  docs/storage.md
  docs/storage/dataset.md
  docs/storage/key_value_store.md
  docs/storage/request_queue.md
  docs/tutorials/integrations.md
  docs/web_scraping_101/web_scraping_techniques.md
Labels: enhancement, medium priority, capitalized

#260 [DO NOT MERGE] Rename 'app' to 'console' and my.apify.com to console.apify.com
  README.md
  docs/access_rights.md
  docs/access_rights/organization_account.md
  docs/access_rights/organization_account/how_to_use.md
  docs/actors.md
  docs/actors/development/continuous_integration.md
  docs/actors/paid_actors.md
  docs/actors/publishing.md
  docs/actors/publishing/naming_your_actor.md
  docs/actors/running.md
  docs/actors/running/compute_units.md
  docs/actors/running/input.md
  docs/actors/tasks/create.md
  docs/actors/tasks/run.md
  docs/api_v2/api_v2_reference.apib
  docs/monitoring.md
  docs/proxy.md
  docs/proxy/connection_settings.md
  docs/proxy/datacenter_proxy/examples.md
  docs/proxy/google_serp_proxy/examples.md
  docs/proxy/residential_proxy.md
  docs/schedules.md
  docs/storage.md
  docs/storage/dataset.md
  docs/storage/key_value_store.md
  docs/storage/request_queue.md
  docs/tutorials/analyze_pages_and_fix_errors.md
  docs/tutorials/crawl_urls_from_a_google_sheet.md
  docs/tutorials/integrations.md
  docs/tutorials/integrations/run_actor_and_retrieve_data_via_api.md
  docs/tutorials/quick_start.md
  docs/tutorials/scrape_websites_using_the_sitemap.md
Labels: debt
