Repository apify/apify-docs, pull requests merged in 2021-06, with the labels that each got.

#242 Proxy: fix line length
  docs/proxy/connection_settings.md
Labels: adhoc

#240 Add authentication bearer info for API requests
  docs/api_v2/api_v2_reference.apib
  docs/schedules.md
  docs/storage.md
  docs/storage/dataset.md
  docs/storage/key_value_store.md
  docs/storage/request_queue.md
  docs/tutorials/integrations.md
Labels: documentation

#252 Create the API Client for Python page, add it to menu
  docs/apify_client_python.md
  docs/cli.md
  docs/sdk.md
Labels: adhoc, enhancement

#257 Update resource name lengths
  docs/actors/publishing/naming_your_actor.md
  docs/actors/tasks/configure.md
  docs/schedules.md
Labels: debt
