Repository apify/apify-docs, pull requests merged in 2022-10, with the labels that each got.

#459 Fix crawl from google file tutorial and run build
  .markdownlint.json
  content/academy/anti_scraping/techniques/images/dont-fingerprint-me.webp
  content/docs/tutorials/crawl_urls_from_a_google_sheet.md
  content/docs/tutorials/images/link-remote-file.png
  content/docs/tutorials/images/link-remote-file.webp
Labels: bug, adhoc, t-web

#460 fix(docs): removed publishing actors link from homepage
  content/docs/homepage_content.json
Labels: bug, t-web

#456 Update webhooks section
  content/docs/access_rights/organization_account.md
  content/docs/access_rights/organization_account/how_to_use.md
  content/docs/actors.md
  content/docs/integrations.md
  content/docs/integrations/images/api-token.png
  content/docs/integrations/images/api-token.webp
  content/docs/integrations/images/integrations-tab.png
  content/docs/integrations/images/integrations-tab.webp
  content/docs/integrations/images/slack-apify-message.png
  content/docs/integrations/images/slack-apify-message.webp
  content/docs/integrations/images/slack-integration-setup.png
  content/docs/integrations/images/slack-integration-setup.webp
  content/docs/integrations/slack.md
  content/docs/integrations/webhooks.md
  content/docs/integrations/webhooks/actions.md
  content/docs/integrations/webhooks/ad_hoc_webhooks.md
  content/docs/integrations/webhooks/events.md
  content/docs/monitoring.md
  content/docs/monitoring/monitor_shared_datasets.md
  content/docs/schedules.md
  content/docs/storage/dataset.md
  content/docs/storage/key_value_store.md
  content/docs/storage/request_queue.md
  content/docs/tutorials.md
  content/docs/tutorials/analyze_pages_and_fix_errors.md
  content/docs/tutorials/images/api-token.png
  content/docs/tutorials/images/api-token.webp
  content/docs/tutorials/run_actor_and_retrieve_data_via_api.md
  content/docs/tutorials/use_apify_from_php.md
Labels: t-web

#461 Add user usage endpoints to API docs
  content/docs/api_v2/api_v2_reference.apib
Labels: t-web

#463 Add docs for secure input
  .github/workflows/pr_toolkit.yml
  content/docs/actors.md
  content/docs/actors/development/images/secret-input-editor.png
  content/docs/actors/development/images/secret-input-editor.webp
  content/docs/actors/development/input_schema.md
  content/docs/actors/development/secret_input.md
Labels: adhoc, t-platform

#468 Fix null being converted to empty object in the examples
  content/docs/api_v2/api_v2_reference.apib
Labels: bug, adhoc, t-web
