Repository apify/apify-docs, pull requests merged in 2022-05, with the labels that each got.

#361 Add a mention of `apify vis` to input schema docs
  content/docs/actors/development/input_schema.md
Labels: adhoc

#368 Update deploying section
  content/academy/apify_platform/deploying_your_code.md
  content/academy/apify_platform/deploying_your_code/deploying.md
  content/academy/apify_platform/images/deployment-workflow.png
  content/academy/apify_platform/images/deployment-workflow.webp
  content/academy/apify_platform/images/supported-languages.jpg
  content/academy/apify_platform/images/supported-languages.webp
  content/academy/expert_scraping_with_apify/images/select-source-location.jpg
  content/academy/expert_scraping_with_apify/images/select-source-location.png
  content/academy/expert_scraping_with_apify/images/select-source-location.webp
Labels: academy

#374 GLOSSARY: Change tools ordering, fix typos, edit overview pages
  content/academy/concepts.md
  content/academy/glossary.md
  content/academy/puppeteer_playwright.md
  content/academy/tools.md
  content/academy/tools/apify_cli.md
  content/academy/tools/modheader.md
  content/academy/tools/postman.md
  content/academy/tools/proxyman.md
  content/academy/tools/switchyomega.md
Labels: academy

#373 Add overview file check for folders
  src/parser.js
Labels: enhancement

#372 Browser contexts lesson (Playwright/Puppeteer)
  content/academy/puppeteer_playwright.md
  content/academy/puppeteer_playwright/browser_contexts.md
  content/academy/puppeteer_playwright/images/dual-contexts.jpg
  content/academy/puppeteer_playwright/images/dual-contexts.webp
  content/academy/puppeteer_playwright/proxies.md
  content/academy/puppeteer_playwright/reading_intercepting_requests.md
Labels: academy

#371 Update actor and proxy docs, add sections to API docs
  content/docs/actors/development/source_code.md
  content/docs/api_v2/api_v2_reference.apib
  content/docs/proxy.md
Labels: documentation

#378 Add new actor environment variables
  content/docs/actors/development/environment_variables.md
Labels: adhoc
