Repository apify/apify-docs, pull requests merged in 2022-11, with the labels that each got.

#475 Add 502 code docs to proxy page
  content/docs/proxy.md
Labels: t-web

#474 feat: Drop basic settings mentions
  content/docs/actors/tasks.md
  content/docs/storage.md
Labels: t-console

#476 fix: Fix bad casing
  content/docs/storage.md
Labels: t-console

#472 feat(actors): add build memory for paid plans
  content/docs/actors/development/builds.md
  content/docs/actors/limits.md
Labels: t-platform

#477 Improve docs related to actor specs
  content/academy/deploying_your_code/deploying.md
  content/docs/actors/development/input_schema.md
  content/docs/actors/development/output_schema.md
  content/docs/actors/development/source_code.md
Labels: t-c&c
