Repository apify/apify-docs, pull requests merged in 2023-08, with the labels that each got.

#658 feat: Add actor min/max memory to actor.json doc
  sources/platform/actors/development/actor_definition/actor_json.md
Labels: t-c&c

#664 docs: fix imports of cheerio in examples
  sources/academy/tutorials/node_js/dealing_with_dynamic_pages.md
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/first_crawl.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/recap_extraction_basics.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/relative_urls.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/scraping_the_data.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_continued.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/project_setup.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/save_to_csv.md
  sources/platform/actors/development/actor_definition/actor_json.md
Labels: debt, t-tooling

#663 fix: add missing python editor
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-platform

#668 feat: update concurrent runs limits
  sources/platform/limits.md
Labels: t-c&c

#665 feat: Updated academy tutorial for creating Actors
  sources/academy/platform/getting_started/creating_actors.md
  sources/academy/platform/getting_started/images/actor-input-tab.png
  sources/academy/platform/getting_started/images/actor-run-dataset.png
  sources/academy/platform/getting_started/images/actor-run.png
  sources/academy/platform/getting_started/images/actor-tips.png
  sources/academy/platform/getting_started/images/create-actor-cli.png
  sources/academy/platform/getting_started/images/create-actor-from-source-code.png
  sources/academy/platform/getting_started/images/create-actor-from-templates.png
  sources/academy/platform/getting_started/images/create-actor-git.png
  sources/academy/platform/getting_started/images/create-actor-template-detail-page.png
  sources/academy/platform/getting_started/images/create-actor-template-javascript-card.png
  sources/academy/platform/getting_started/images/create-actor-template-locally.png
  sources/academy/platform/getting_started/images/create-actor-templates-go-to-library.png
  sources/academy/platform/getting_started/images/create-actor-web-ide.png
  sources/academy/platform/getting_started/images/create-new-actor.png
  sources/academy/platform/getting_started/images/multifile-editor.png
Labels: t-web

#671 feat: rename paid actor to rental actor
  sources/academy/platform/get_most_of_actors/index.md
  sources/platform/actors/development/actor_definition/index.md
  sources/platform/actors/publishing/monetize.mdx
  sources/platform/actors/running/store.md
Labels: adhoc, t-c&c

#676 feat: proofread and edit for a2a docs
  sources/platform/integrations/actors/implementation_details.md
  sources/platform/integrations/actors/index.md
  sources/platform/integrations/actors/integrating_actors_via_api.md
  sources/platform/integrations/actors/integration_ready_actors.md
Labels: adhoc

#678 feat: Mention that ~ can be used without username to access your own stores
  sources/platform/storage/index.md
Labels: adhoc, t-console

#677 feat: explain usage usd on run and build objects
  sources/platform/actors/running/usage_and_resources.md
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-c&c

#679 feat: add store api endpoint
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#688 chore: Update Apify CLI installation instructions via Homebrew
  sources/platform/actors/development/quick_start/start_locally.md
  sources/platform/actors/development/quick_start/start_web_ide.md
Labels: adhoc, t-platform
