Repository apify/apify-docs, pull requests merged in 2023-12, with the labels that each got.

#772 chore: Adding info on redirects to README.md
  README.md
Labels: adhoc, t-platform

#771 fix: Fixing and old tutorial link from Webscraper README
  nginx.conf
Labels: bug, adhoc, t-platform

#774 fix: changes to style guide & contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: t-docs

#785 docs: change e-mail address for readme submission
  sources/academy/platform/get_most_of_actors/guidelines_for_writing.md
Labels: academy, content

#787 chore: remove unused dependency on undici + update GH pages deps
  .github/workflows/docs.yaml
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#788 fix: Fixed monetize your code banner button link
  src/pages/index.tsx
Labels: bug, adhoc, t-web

#777 docs: rewrite schedules section
  sources/platform/images/schedule-actor-run.png
  sources/platform/images/schedule-add-tasks.png
  sources/platform/images/schedule-settings.png
  sources/platform/images/schedule-setup.png
  sources/platform/images/schedules-actor-input.png
  sources/platform/images/schedules-overview.png
  sources/platform/images/schedules-setup-tool.png
  sources/platform/images/schedules-task-input.png
  sources/platform/schedules.md
Labels: t-docs

#792 docs: integrate new og:image links
  apify-docs-theme/src/config.js
  package-lock.json
  package.json
  patches/@docusaurus+mdx-loader+2.4.3.patch
Labels: documentation, adhoc, t-tooling

#794 fix: use `--legacy-peer-deps` in the CI
  .github/workflows/publish-theme.yaml
Labels: bug, adhoc, t-tooling

#795 docs: fix broken links
  sources/platform/storage/dataset.md
Labels: t-docs

#790 docs: add new Apify Console docs
  sources/platform/console/billing.md
  sources/platform/console/images/console-actors-recently-used.png
  sources/platform/console/images/console-actors-runs.png
  sources/platform/console/images/console-billing-current-period.png
  sources/platform/console/images/console-billing-historical-usage-by-actors.png
  sources/platform/console/images/console-billing-historical-usage.png
  sources/platform/console/images/console-billing-invoices.png
  sources/platform/console/images/console-billing-limits.png
  sources/platform/console/images/console-billing-pricing.png
  sources/platform/console/images/console-billing-subscription.png
  sources/platform/console/images/console-homepage.png
  sources/platform/console/images/console-login.png
  sources/platform/console/images/console-signup.png
  sources/platform/console/images/console-store.png
  sources/platform/console/index.md
  sources/platform/console/settings.md
  sources/platform/console/store.md
Labels: documentation, t-docs
