Repository apify/apify-docs, pull requests merged in 2023-04, with the labels that each got.

#563 Review: restructuring + simplified
  sources/platform/monitoring/images/alerts.png
  sources/platform/monitoring/images/daily-run-statuses.png
  sources/platform/monitoring/images/metric-options.png
  sources/platform/monitoring/images/monitoring.png
  sources/platform/monitoring/images/notifications.png
  sources/platform/monitoring/images/run-statistics-chart.png
  sources/platform/monitoring/index.md
Labels: adhoc

#560 feat: Add api doc for maxItems param
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-c&c

#536 feat: Updating integrations section
  .nvmrc
  sources/platform/actors/index.md
  sources/platform/actors/publishing/index.mdx
  sources/platform/collaboration/organization_account/how_to_use.md
  sources/platform/collaboration/organization_account/index.md
  sources/platform/integrations/api.md
  sources/platform/integrations/drive.md
  sources/platform/integrations/github.md
  sources/platform/integrations/gmail.md
  sources/platform/integrations/images/api-token-organization.png
  sources/platform/integrations/images/apify-store.png
  sources/platform/integrations/index.md
  sources/platform/integrations/index.mdx
  sources/platform/integrations/langchain.md
  sources/platform/integrations/make.md
  sources/platform/integrations/slack.md
  sources/platform/integrations/webhooks/index.md
  sources/platform/schedules.md
  sources/platform/storage/dataset.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
  src/components/Card.jsx
  src/components/Cards.module.css
  static/img/platform/integrations/airbyte.svg
  static/img/platform/integrations/appmixer.svg
  static/img/platform/integrations/asana.svg
  static/img/platform/integrations/drive.svg
  static/img/platform/integrations/git.svg
  static/img/platform/integrations/github.svg
  static/img/platform/integrations/gmail.svg
  static/img/platform/integrations/hevo.svg
  static/img/platform/integrations/keboola.svg
  static/img/platform/integrations/langchain.png
  static/img/platform/integrations/make.svg
  static/img/platform/integrations/slack.svg
  static/img/platform/integrations/transposit.svg
  static/img/platform/integrations/trello.svg
  static/img/platform/integrations/webhook.svg
  static/img/platform/integrations/webhooks.svg
  static/img/platform/integrations/zapier.svg
Labels: t-console

#566 docs: Add docs for Actor monorepos
  sources/platform/actors/development/deployment/source_types.md
Labels: adhoc, t-platform

#572 fix: SVG clip-path does not work in Firefox
  src/pages/img/rectangle-python.svg
Labels: t-tooling

#559 feat: Updated monitoring docs
  sources/platform/monitoring/actor_or_task_run_failure.md
  sources/platform/monitoring/check_data_quality.md
  sources/platform/monitoring/images/alerts.png
  sources/platform/monitoring/images/covid-config.png
  sources/platform/monitoring/images/covid-multiple-tasks.png
  sources/platform/monitoring/images/covid-validate-schema.png
  sources/platform/monitoring/images/customize-notifications.png
  sources/platform/monitoring/images/daily-run-statuses.png
  sources/platform/monitoring/images/email-notification.png
  sources/platform/monitoring/images/enable-dashboard.png
  sources/platform/monitoring/images/in-app-notification.png
  sources/platform/monitoring/images/iphone-check-duplicates.png
  sources/platform/monitoring/images/iphone-task.png
  sources/platform/monitoring/images/iphone-validate-data.png
  sources/platform/monitoring/images/joke-duplicates.png
  sources/platform/monitoring/images/joke-monitoring-config.png
  sources/platform/monitoring/images/joke-schedule.png
  sources/platform/monitoring/images/joke-scraper-tasks.png
  sources/platform/monitoring/images/joke-storage.png
  sources/platform/monitoring/images/joke-validate-schema.png
  sources/platform/monitoring/images/metric-options.png
  sources/platform/monitoring/images/monitoring-dashboard.png
  sources/platform/monitoring/images/monitoring-in-store.png
  sources/platform/monitoring/images/monitoring.png
  sources/platform/monitoring/images/notifications.png
  sources/platform/monitoring/images/puppies-config.png
  sources/platform/monitoring/images/puppies-failed-run.png
  sources/platform/monitoring/images/puppies-schema.png
  sources/platform/monitoring/images/puppies-task.png
  sources/platform/monitoring/images/run-statistics-chart.png
  sources/platform/monitoring/index.md
  sources/platform/monitoring/monitor_multiple_tasks.md
  sources/platform/monitoring/monitor_shared_datasets.md
Labels: t-console

#582 feat: Replaced all mentions about multiple source file with Web IDE
  README.md
  sources/academy/platform/deploying_your_code/deploying.md
  sources/academy/platform/expert_scraping_with_apify/managing_source_code.md
  sources/platform/actors/development/source_code.md
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-web
