Repository apify/apify-docs, pull requests merged in 2023-06, with the labels that each got.

#603 feat: Add shouldInterpolateStrings explanation to docs and api blueprint
  sources/platform/api_v2/api_v2_reference.apib
  sources/platform/integrations/webhooks/actions.md
Labels: adhoc, t-console

#609 docs: replace PHP tutorial
  apify-docs-theme/src/config.js
  nginx.conf
  sources/academy/tutorials/php/using_apify_from_php.md
  sources/academy/tutorials/php/using_apify_scraper_with_php.md
Labels: adhoc, t-console

#621 fix: Fix how to call Slack command
  sources/platform/integrations/slack.md
Labels: adhoc, t-platform

#625 feat: pull command
  sources/platform/actors/development/quick_start/images/actor-pull.png
  sources/platform/actors/development/quick_start/start_web_ide.md
Labels: t-web

#607 feat: increase build memory size
  sources/platform/limits.md
Labels: adhoc, t-console

#620 feat: add academy api client access
  sources/academy/platform/getting_started/apify_client.md
  sources/academy/platform/getting_started/images/api-button.png
Labels: t-web
