Repository apify/apify-docs, pull requests merged in 2023-11, with the labels that each got.

#745 fix: Added flatten param into API reference get dataset items
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#759 fix: Added missing token to docs build action
  .github/workflows/docs.yaml
Labels: bug, adhoc, t-web

#756 docs: fix typo in continuous integration page
  sources/platform/actors/development/deployment/continuous_integration.md
Labels: adhoc, t-tooling

#757 docs: add a note on compatibility between JSON schema and Actor input schema
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-tooling

#768 feat: Stress prefill section in Actor integration docs
  sources/platform/integrations/actors/integration_ready_actors.md
Labels: t-console
