Repository apify/apify-docs, pull requests merged in 2023-03, with the labels that each got.

#530 feat: Improving security and limits sections
  sources/platform/actors/images/limits/usage-limits.png
  sources/platform/actors/images/security/whitepaper-cover.png
  sources/platform/actors/limits.md
  sources/platform/actors/security.md
Labels: t-platform

#534 fix: ensure custom searchbox is used in all the projects
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  apify-docs-theme/src/theme/SearchMetadata/index.js
  docusaurus.config.js
  package-lock.json
Labels: t-tooling

#535 Improving Mara's docs on actors in store
  sources/platform/actors/index.md
  sources/platform/actors/running/store.md
Labels: adhoc, t-c&c

#541 feat: add pay per result docs
  sources/platform/actors/running/images/store/console_pay_per_result_tag.png
  sources/platform/actors/running/images/store/example_run_usage.png
  sources/platform/actors/running/images/store/free_vs_paid_actors.png
  sources/platform/actors/running/images/store/paid-actors-billing.png
  sources/platform/actors/running/images/store/paid-actors-issues-tab.png
  sources/platform/actors/running/images/store/paid-actors-store.png
  sources/platform/actors/running/images/store/paid-actors-trial.png
  sources/platform/actors/running/images/store/pay_per_result_actor_store_card.png
  sources/platform/actors/running/images/store/pay_per_result_billing_usage_section.png
  sources/platform/actors/running/images/store/pay_per_result_run_detail.png
  sources/platform/actors/running/images/store/pay_per_result_run_list.png
  sources/platform/actors/running/store.md
Labels: adhoc, t-c&c

#538 feat: add missing actor run attributes
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#546 feat: Graduate the Python SDK out of beta
  apify-docs-theme/src/config.js
  src/pages/index.tsx
Labels: adhoc, t-platform

#539 fix: Fixing wrong example #417
  sources/academy/webscraping/puppeteer_playwright/browser.md
Labels: t-platform

#551 fix: optional subtitle `to` link, academy sidebar
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  docusaurus.config.js
  sources/academy/index.mdx
  sources/academy/sidebars.js
Labels: t-tooling
