Repository apify/apify-docs, pull requests merged in 2023-09, with the labels that each got.

#687 feat: Add Zapier docs
  sources/platform/integrations/images/zapier-action-1.png
  sources/platform/integrations/images/zapier-action-2.png
  sources/platform/integrations/images/zapier-action-3.png
  sources/platform/integrations/images/zapier-new-connection.png
  sources/platform/integrations/images/zapier-trigger-2.png
  sources/platform/integrations/images/zapier-trigger.png
  sources/platform/integrations/index.mdx
  sources/platform/integrations/zapier.md
Labels: documentation, t-platform

#672 feat: Add docs for actor-to-actor integrations
  sources/platform/actors/development/index.md
  sources/platform/integrations/actors/images/available_variables.png
  sources/platform/integrations/actors/images/integration_triggers.png
  sources/platform/integrations/actors/images/integrations_add.png
  sources/platform/integrations/actors/images/specific_vs_generic_integrations.png
  sources/platform/integrations/actors/index.md
  sources/platform/integrations/actors/integrating_actors_via_api.md
  sources/platform/integrations/actors/integration_ready_actors.md
  sources/platform/integrations/index.mdx
Labels: t-console, sprint goal

#698 feat: Add docs for flowise and llmama index
  sources/platform/integrations/flowise.md
  sources/platform/integrations/images/flowise-2.png
  sources/platform/integrations/images/flowise.png
  sources/platform/integrations/llama.md
Labels: adhoc, t-platform

#707 feat: Add description of integration prefill feature
  sources/platform/integrations/actors/images/available_variables.png
  sources/platform/integrations/actors/index.md
  sources/platform/integrations/actors/integration_ready_actors.md
Labels: adhoc, t-console

#706 chore: Removed references to issuesEnabled
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-c&c

#713 docs: Added multiselect to input schema specification
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: t-console

#709 feat: add Run on Apify button support
  .github/workflows/apiary.yaml
  .github/workflows/docs.yaml
  .github/workflows/publish-theme.yaml
  .github/workflows/test.yaml
  apify-docs-theme/src/config.js
  apify-docs-theme/src/roa-loader/index.js
  apify-docs-theme/src/roa-loader/package.json
  apify-docs-theme/src/theme/MDXComponents/Code.js
  apify-docs-theme/src/theme/MDXComponents/Details.js
  apify-docs-theme/src/theme/MDXComponents/Head.js
  apify-docs-theme/src/theme/MDXComponents/Heading.js
  apify-docs-theme/src/theme/MDXComponents/Img/index.js
  apify-docs-theme/src/theme/MDXComponents/Img/styles.module.css
  apify-docs-theme/src/theme/MDXComponents/Pre.js
  apify-docs-theme/src/theme/MDXComponents/Ul/index.js
  apify-docs-theme/src/theme/MDXComponents/Ul/styles.module.css
  apify-docs-theme/src/theme/MDXComponents/index.js
  apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
  apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.module.css
  apify-docs-theme/src/theme/custom.css
  sources/academy/.eslintrc.json
  sources/academy/tutorials/node_js/caching_responses_in_puppeteer.js
  sources/academy/tutorials/node_js/caching_responses_in_puppeteer.md
  sources/academy/tutorials/node_js/dealing_with_dynamic_pages.js
  sources/academy/tutorials/node_js/dealing_with_dynamic_pages.md
  sources/academy/tutorials/node_js/scraping_from_sitemaps.js
  sources/academy/tutorials/node_js/scraping_from_sitemaps.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.js
  sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.md
Labels: product roadmap, t-tooling
