Repository apify/apify-docs, pull requests merged in 2023-10, with the labels that each got.

#719 feat: remove last part of breadcrumbs
  apify-docs-theme/src/theme/ColorModeToggle/index.jsx
  apify-docs-theme/src/theme/DocBreadcrumbs/Items/Home/index.js
  apify-docs-theme/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
  apify-docs-theme/src/theme/DocBreadcrumbs/index.js
  apify-docs-theme/src/theme/DocBreadcrumbs/styles.module.css
  apify-docs-theme/src/theme/DocSidebarItem/Link/index.jsx
  apify-docs-theme/src/theme/Footer/index.jsx
  apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
  sources/academy/index.mdx
  sources/platform/index.mdx
  src/theme/DocBreadcrumbs/Items/Home/styles.module.css
Labels: t-tooling

#705 feat: add actor integration testing docs
  sources/platform/integrations/actors/images/integrations_test_options.png
  sources/platform/integrations/actors/index.md
Labels: adhoc, t-console, tested

#723 feat: improve paid actors docs for devs
  sources/academy/platform/get_most_of_actors/images/actor_analytics.png
  sources/academy/platform/get_most_of_actors/images/actor_insights.png
  sources/academy/platform/get_most_of_actors/images/billing-details.png
  sources/academy/platform/get_most_of_actors/images/monetization_section.png
  sources/academy/platform/get_most_of_actors/images/monetization_wizard.png
  sources/academy/platform/get_most_of_actors/images/monetize_actor_set_up_monetization.png
  sources/academy/platform/get_most_of_actors/images/scraper-earnings-example.webp
  sources/academy/platform/get_most_of_actors/images/scraper-example.webp
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/actors/publishing/testing.mdx
  sources/platform/actors/running/store.md
Labels: t-c&c, tested

#725 fix(docs): actor status message api params
  sources/platform/api_v2/api_v2_reference.apib
Labels: bug, adhoc, t-console

#729 fix: broken link to Python SDK
  sources/platform/storage/request_queue.md
Labels: bug, documentation, adhoc, t-tooling

#728 fix: replace old input schema image
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-example.png
Labels: bug, documentation, adhoc, t-console

#727 feat: Add docs for run/build DELETE endpoint
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-c&c

#716 feat: update run resurrection docs
  sources/platform/actors/running/runs_and_builds.md
Labels: adhoc, t-console

#734 chore: bump @apify/docs-search-modal version
  apify-docs-theme/package.json
  package-lock.json
Labels: adhoc, t-tooling

#720 feat: add info about webhook headers and description
  sources/platform/api_v2/api_v2_reference.apib
  sources/platform/integrations/webhooks/actions.md
Labels: documentation, t-console

#741 feat: add scrape single url action into Zapier docs
  sources/platform/integrations/images/zapier-action-1.png
  sources/platform/integrations/zapier.md
Labels: t-platform
