Repository apify/apify-docs, pull requests merged in 2023-05, with the labels that each got.

#585 feat: Rename APIFY_ACTOR_MAX_ITEMS to ACTOR_MAX_PAID_DATASET_ITEMS
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-c&c

#586 refactor: use google tag manager
  apify-docs-theme/package.json
  apify-docs-theme/src/config.js
  package-lock.json
Labels: t-tooling

#589 fix: Update max `waitForFinish` value
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/platform/api_v2/api_v2_reference.apib
Labels: bug, adhoc, t-platform

#587 feat: add usage usd under run and build
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#591 feat: Cherry-picking notes on monorepos from Franta
  sources/platform/actors/development/source_code.md
Labels: adhoc, t-platform

#590 chore: prepare for reusable workflows
  .github/workflows/deploy.yaml
  .github/workflows/invalidate.yaml
  nginx.conf
Labels: adhoc, t-platform

#597 feat: improve pay per result docs
  sources/platform/actors/running/images/store/pay_per_result_actor_items.png
  sources/platform/actors/running/images/store/pay_per_result_max_items.png
  sources/platform/actors/running/store.md
Labels: t-c&c

#598 chore: Use new secrets in CI
  .github/workflows/publish-theme.yaml
Labels: adhoc, debt, t-platform

#601 docs: fix secret image url
  sources/platform/actors/development/secret_input.md
Labels: bug, adhoc, t-c&c

#602 chore: invalidate CloudFront after every GitHub pages deploy
  .github/workflows/docs.yaml
  .github/workflows/invalidate.yaml
Labels: adhoc, t-platform
