Repository apify/apify-docs, pull requests merged in 2024-12, with the labels that each got.

#1315 docs: aws bedrock agents
  sources/platform/integrations/ai/aws_bedrock.md
  sources/platform/integrations/images/aws-bedrock-agent-builder-create-action.png
  sources/platform/integrations/images/aws-bedrock-agent-builder.png
  sources/platform/integrations/images/aws-bedrock-agent-chat.png
  sources/platform/integrations/images/aws-bedrock-ai-agent.png
  sources/platform/integrations/images/aws-bedrock-create-agent.png
  sources/platform/integrations/images/aws-bedrock-menu.png
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/aws-bedrock.png
Labels: t-ai

#1308 docs: add haystack tile to AI integrations, replace Apify Store screenshot
  sources/platform/integrations/images/apify-store.png
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/haystack.png
Labels: t-ai

#1322 fix(request-queue): Update request queue locking docs
  sources/platform/storage/request_queue.md
Labels: t-platform

#1320 feat: Add `ACTOR_FULL_NAME` and `ACTOR_BUILD_TAGS` environment variables
  sources/platform/actors/development/programming_interface/environment_variables.md
Labels: adhoc, t-platform

#1343 docs: fix formatting
  sources/platform/actors/development/quick_start/index.mdx
Labels: documentation, adhoc, t-docs

#1341 docs: add marketing playbook to docs
  sources/academy/platform/get_most_of_actors/actor_readme.md
  sources/academy/platform/get_most_of_actors/guidelines_for_writing.md
  sources/academy/platform/get_most_of_actors/index.md
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  sources/academy/platform/get_most_of_actors/naming_your_actor.md
  sources/academy/platform/get_most_of_actors/seo_and_promotion.md
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/publishing/index.mdx
  sources/platform/actors/publishing/publish.mdx
Labels: documentation, t-academy, t-docs

#1337 docs: update monetize your Actor section
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  vale.ini
Labels: documentation, t-academy, t-docs

#1344 fix: openapi docs improvements
  apify-docs-theme/src/theme/custom.css
  docusaurus.config.js
  package-lock.json
  package.json
  patches/docusaurus-theme-openapi-docs+0.0.0-961.patch
  src/theme/DocCard/index.js
  src/theme/DocCard/styles.module.css
Labels: adhoc, t-tooling

#1342 fix: parse project changelogs with `remark`
  apify-docs-theme/package.json
  apify-docs-theme/src/markdown.js
  package-lock.json
Labels: adhoc, t-tooling

#1323 feat(request-queue): Update RQ listAndLock API with latest API changes
  apify-api/openapi/components/schemas/request-queues/GetHeadAndLockResponse.yaml
  apify-api/openapi/components/schemas/request-queues/RequestQueue.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@head@lock.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}@lock.yaml
Labels: adhoc, t-platform

#1352 feat: improve documentation for scoped tokens
  sources/platform/integrations/images/api-token-organization.png
  sources/platform/integrations/images/api-token-scoped-default-storage-access.png
  sources/platform/integrations/images/api-token-scoped-restricted-access-active.png
  sources/platform/integrations/images/api-token-scoped-run-modes.png
  sources/platform/integrations/images/api-token-scoped-run-tasks.png
  sources/platform/integrations/images/api-token.png
  sources/platform/integrations/programming/api.md
Labels: t-platform

#1356 docs: Add Python variant example of catching dataset validation errors
  sources/platform/actors/development/actor_definition/dataset_schema/validation.md
Labels: documentation, t-tooling

#1364 fix: Add redirect from crawlee.dev/python/docs
  nginx.conf
Labels: adhoc, t-tooling
