Repository apify/apify-docs, pull requests merged in 2024-09, with the labels that each got.

#1175 feat: Remove smartlook and add intercom messenger
  .github/workflows/deploy.yaml
  .github/workflows/docs.yaml
  .github/workflows/lychee.yml
  .github/workflows/test.yaml
  apify-docs-theme/package.json
  apify-docs-theme/src/config.js
  docusaurus.config.js
  package-lock.json
Labels: t-web

#1144 feat: Deprecating the old API documentation
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-tooling

#1176 chore: bump Docusaurus to v3
  .markdownlint.json
  apify-docs-theme/package.json
  apify-docs-theme/src/theme/DocBreadcrumbs/index.js
  apify-docs-theme/src/theme/DocSidebarItem/Link/index.jsx
  apify-docs-theme/src/theme/NavbarItem/ComponentTypes.jsx
  docusaurus.config.js
  package-lock.json
  package.json
  patches/@docusaurus+mdx-loader+2.4.3.patch
  sources/academy/glossary/tools/postman.md
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/academy/platform/get_most_of_actors/actor_readme.md
  sources/academy/platform/get_most_of_actors/naming_your_actor.md
  sources/academy/platform/get_most_of_actors/seo_and_promotion.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/apify_scrapers/cheerio_scraper.md
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/academy/tutorials/apify_scrapers/puppeteer_scraper.md
  sources/academy/tutorials/apify_scrapers/web_scraper.md
  sources/academy/tutorials/node_js/add_external_libraries_web_scraper.md
  sources/academy/tutorials/node_js/block_requests_puppeteer.md
  sources/academy/tutorials/node_js/processing_multiple_pages_web_scraper.md
  sources/academy/tutorials/node_js/scraping_from_sitemaps.md
  sources/academy/tutorials/node_js/scraping_urls_list_from_google_sheets.md
  sources/academy/tutorials/node_js/using_proxy_to_intercept_requests_puppeteer.md
  sources/legal/latest/policies/gdpr-information.md
  sources/legal/old/general-terms-and-conditions-2022.md
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/index.md
  sources/platform/actors/development/deployment/source_types.md
  sources/platform/actors/publishing/publish.mdx
  sources/platform/console/index.md
  sources/platform/integrations/ai/haystack.md
  sources/platform/integrations/ai/langchain.md
  sources/platform/proxy/usage.md
  sources/platform/storage/key_value_store.md
  src/components/ApiLink.jsx
  src/theme/DocItem/Layout/index.js
  src/theme/DocItem/Metadata/index.js
Labels: adhoc, t-tooling

#1148 feat(platform): add documentation for scoped API tokens
  sources/platform/integrations/images/api-token-scoped-with-combining-permissions.png
  sources/platform/integrations/images/api-token-scoped.png
  sources/platform/integrations/programming/api.md
Labels: t-platform

#1180 fix: `publish-theme` action uses `secrets.NPM_TOKEN`
  .github/workflows/publish-theme.yaml
Labels: adhoc, t-tooling

#1184 fix: escape MDX characters in changelog (Docusaurus v3)
  apify-docs-theme/src/markdown.js
  apify-docs-theme/src/theme.js
Labels: adhoc, t-tooling

#1187 fix: double wrapping codeblocks in `MDXPre`
  apify-docs-theme/src/theme/MDXComponents/Pre.js
Labels: bug, t-tooling

#1186 fix: remove race condition from the changelog generation
  apify-docs-theme/src/theme.js
Labels: adhoc, t-tooling

#1161 docs: continuous integration rewrite
  apify-docs-theme/src/theme/custom.css
  sources/platform/actors/development/deployment/continuous_integration.md
Labels: t-docs

#1160 docs: rewrite source types document
  sources/platform/actors/development/deployment/images/deployment-keys.png
  sources/platform/actors/development/deployment/index.md
  sources/platform/actors/development/deployment/source_types.md
Labels: t-docs

#1189 fix: make TOC rendering consistent regardless of the page content
  apify-docs-theme/package.json
  apify-docs-theme/src/theme/TOCItems/Tree.jsx
  apify-docs-theme/src/theme/TOCItems/index.jsx
  apify-docs-theme/src/theme/TOCItems/styles.module.css
  package-lock.json
  src/theme/DocItem/Layout/index.js
  src/theme/DocItem/Layout/styles.module.css
Labels: t-tooling

#1192 docs: add comments
  _typos.toml
Labels: t-academy, t-docs

#1195 fix: highlight python snippets with `py` language
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#1108 fix: update lesson to reflect changes in UI and in number of the repos
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
Labels: t-academy

#1197 feat: kick off the Python course (upstream branch)
  docusaurus.config.js
  sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/03_devtools_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/09_crawling.md
  sources/academy/webscraping/scraping_basics_python/_exercises.mdx
  sources/academy/webscraping/scraping_basics_python/images/child-elements.png
  sources/academy/webscraping/scraping_basics_python/images/h1.png
  sources/academy/webscraping/scraping_basics_python/images/product-item.png
  sources/academy/webscraping/scraping_basics_python/images/scraping.png
  sources/academy/webscraping/scraping_basics_python/index.md
Labels: t-academy

#1209 chore: remove patching
  package-lock.json
  package.json
Labels: t-academy, t-tooling, t-docs

#1207 fix: revert details component rendering to pre-v3 state
  apify-docs-theme/src/theme/MDXComponents/Details.js
  apify-docs-theme/src/theme/MDXComponents/index.js
  sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/platform/console/index.md
Labels: t-tooling

#1206 fix(platform): replace "account level" with "account-level"
  sources/platform/integrations/programming/api.md
Labels: t-platform

#1200 feat(platform): explain permission dependencies for scoped tokens
  sources/platform/integrations/images/api-token-scoped-dependencies.png
  sources/platform/integrations/programming/api.md
Labels: t-platform

#1203 docs: Add documentation for Milvus/Zilliz database integration
  sources/platform/integrations/ai/milvus.md
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/milvus.svg
Labels: t-ai

#1198 docs: remove dead link in langchain docs
  sources/platform/integrations/ai/langchain.md
Labels: t-docs

#1204 fix: typos and stylistic improvements
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/academy/tutorials/node_js/filter_blocked_requests_using_sessions.md
  sources/academy/webscraping/anti_scraping/index.md
  sources/academy/webscraping/anti_scraping/mitigation/proxies.md
  sources/academy/webscraping/anti_scraping/techniques/fingerprinting.md
  sources/academy/webscraping/anti_scraping/techniques/rate_limiting.md
  sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
  sources/academy/webscraping/api_scraping/general_api_scraping/locating_and_learning.md
  sources/academy/webscraping/puppeteer_playwright/browser_contexts.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/extracting_data.md
  sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
  sources/academy/webscraping/puppeteer_playwright/proxies.md
  sources/academy/webscraping/puppeteer_playwright/reading_intercepting_requests.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/browser_devtools.md
Labels: t-academy

#1210 docs: update-privacy-policy.md
  sources/legal/latest/policies/privacy-policy.md
Labels: t-docs

#1216 fix: stabilize `DocItem/Layout`
  src/theme/DocItem/Layout/index.js
  src/theme/DocItem/Layout/styles.module.css
Labels: t-tooling

#1219 docs: Update privacy-policy.md
  sources/legal/latest/policies/privacy-policy.md
Labels: t-docs

#1224 docs: Add links to Haystack cookbook examples.
  sources/platform/integrations/ai/haystack.md
Labels: t-ai

#1223 docs: add information regarding session and organization security settings
  sources/platform/collaboration/organization_account/setup.md
  sources/platform/console/settings.md
  sources/platform/console/two-factor-authentication.md
Labels: adhoc, t-console

#1226 feat: mention larger allowed input schema size
  sources/platform/actors/development/actor_definition/input_schema/specification.md
  sources/platform/limits.md
Labels: adhoc, t-platform

#1229 docs: change milvusApiKey to milvusToken
  sources/platform/integrations/ai/milvus.md
Labels: t-ai
