Repository apify/apify-docs, pull requests merged in 2024-01, with the labels that each got.

#810 chore: ui-components version bump
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#811 fix: try to fix the theme publishing CI
  .github/workflows/publish-theme.yaml
Labels: adhoc, t-tooling

#812 chore: make change in theme to trigger publishing
  apify-docs-theme/package.json
Labels: adhoc, t-tooling

#813 fix: propagate the CSS fixes in the theme
  apify-docs-theme/package.json
  apify-docs-theme/src/theme.js
  docusaurus.config.js
  package-lock.json
Labels: adhoc, t-tooling

#828 chore: bump apify ui components to an existing version
  package-lock.json
  package.json
Labels: adhoc

#827 feat: Improve section on string interpolation in webhook payloads
  sources/platform/integrations/webhooks/actions.md
Labels: adhoc, t-console

#841 chore: update `@apify-packages/ui-components` (+ style fixes)
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/CardWithIcon/styles.module.css
  src/components/Cards.module.css
Labels: adhoc, t-tooling
