Repository apify/apify-docs, pull requests merged in 2024-03, with the labels that each got.

#877 fix(landing page): design fixes
  apify-docs-theme/src/theme/custom.css
  src/components/CardWithImageAndContent/styles.module.css
  src/components/Heading.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/OpenSourceCards/styles.module.css
  src/pages/index.module.css
  src/pages/index.tsx
Labels: t-web

#855 feat: lychee link checker from built website version
  .github/styles/Apify/Capitalization.yml
  .github/workflows/lychee.yml
  .lycheeignore
  apify-docs-theme/src/config.js
  sources/academy/glossary/concepts/http_cookies.md
  sources/academy/glossary/tools/modheader.md
  sources/academy/glossary/tools/switchyomega.md
  sources/academy/platform/expert_scraping_with_apify/saving_useful_stats.md
  sources/academy/platform/get_most_of_actors/actor_readme.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/node_js/debugging_web_scraper.md
  sources/academy/tutorials/node_js/optimizing_scrapers.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/injecting_code.md
  sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
  sources/platform/actors/development/actor_definition/output_schema.md
  sources/platform/actors/development/index.md
  sources/platform/actors/running/usage_and_resources.md
  sources/platform/integrations/langchain.md
  sources/platform/integrations/llama.md
  sources/platform/integrations/webhooks/ad_hoc_webhooks.md
  sources/platform/storage/dataset.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
Labels: adhoc, t-tooling

#879 docs: rewrite of flowise integration
  sources/platform/integrations/flowise.md
  sources/platform/integrations/images/flowise-apify-api.png
  sources/platform/integrations/images/flowise-apify-website-crawler.png
  sources/platform/integrations/images/flowise-apify.png
  sources/platform/integrations/images/flowise-start-screen.png
Labels: t-docs

#883 docs: remove sharing info from the Schedules page
  sources/platform/schedules.md
Labels: adhoc, t-platform

#878 docs: updates & rewrites to actors in store page
  sources/platform/actors/running/images/store/billing-paid-actors.png
  sources/platform/actors/running/images/store/pay-per-usage-actor-example.png
  sources/platform/actors/running/images/store/rental-actor-example.png
  sources/platform/actors/running/images/store/rental-actor-trial-example.png
  sources/platform/actors/running/store.md
  vale.ini
Labels: t-docs

#881 docs: rewrites to input and output page
  sources/platform/actors/running/input_and_output.md
Labels: t-docs

#884 docs: runs and builds updates
  sources/platform/actors/running/runs_and_builds.md
Labels: t-docs

#888 fix: update og-image url
  .lycheeignore
  apify-docs-theme/src/config.js
  patches/@docusaurus+mdx-loader+2.4.3.patch
Labels: t-web

#891 fix: examples cards small texts
  apify-docs-theme/src/theme/custom.css
  src/pages/index.module.css
Labels: adhoc, t-web

#893 fix: Update selectors for examples cards titles and descriptions
  apify-docs-theme/src/theme/custom.css
  src/pages/index.module.css
Labels: adhoc, t-web

#890 feat: Setup Smartlook [internal]
  .github/workflows/deploy.yaml
  .github/workflows/lychee.yml
  .github/workflows/test.yaml
  apify-docs-theme/src/config.js
  package-lock.json
  package.json
Labels: t-web

#894 fix: Smartlook build token [internal]
  .github/workflows/docs.yaml
Labels: adhoc, t-web

#895 docs: remove DELETE permission from Collaboration section
  sources/platform/collaboration/list_of_permissions.md
Labels: t-platform

#889 docs: update tasks section
  sources/platform/actors/running/images/tasks/create-task-configure.png
  sources/platform/actors/running/images/tasks/create-task-run.png
  sources/platform/actors/running/images/tasks/create-task-settings.png
  sources/platform/actors/running/images/tasks/create-task.png
  sources/platform/actors/running/images/tasks/tasks-create-configure.png
  sources/platform/actors/running/images/tasks/tasks-create-task.png
  sources/platform/actors/running/images/tasks/tasks-start-after-configuration.png
  sources/platform/actors/running/images/tasks/tasks-start-button.png
  sources/platform/actors/running/tasks.md
Labels: t-docs

#905 chore: Just testing the CI/CD
  README.md
Labels: adhoc, t-platform

#886 docs: update usage and resources
  sources/platform/actors/running/images/usage_and_resources/usage-and-resources-runs-usage-details.png
  sources/platform/actors/running/images/usage_and_resources/usage-and-resources-runs-usage.png
  sources/platform/actors/running/usage_and_resources.md
Labels: t-docs
