Repository apify/apify-docs, pull requests merged in 2024-06, with the labels that each got.

#1042 docs: reorganize integrations sidebar
  sources/platform/actors/development/actor_definition/index.md
  sources/platform/actors/development/deployment/source_types.md
  sources/platform/integrations/actors/_category_.yml
  sources/platform/integrations/actors/index.md
  sources/platform/integrations/actors/integration_ready_actors.md
  sources/platform/integrations/ai/_category_.yml
  sources/platform/integrations/ai/flowise.md
  sources/platform/integrations/ai/langchain.md
  sources/platform/integrations/ai/llama.md
  sources/platform/integrations/ai/pinecone.md
  sources/platform/integrations/data-storage/_category_.yml
  sources/platform/integrations/data-storage/airbyte.md
  sources/platform/integrations/data-storage/drive.md
  sources/platform/integrations/data-storage/keboola.md
  sources/platform/integrations/index.mdx
  sources/platform/integrations/integrate_with_apify.md
  sources/platform/integrations/programming/_category_.yml
  sources/platform/integrations/programming/api.md
  sources/platform/integrations/programming/github.md
  sources/platform/integrations/programming/webhooks/actions.md
  sources/platform/integrations/programming/webhooks/ad_hoc_webhooks.md
  sources/platform/integrations/programming/webhooks/events.md
  sources/platform/integrations/programming/webhooks/index.md
  sources/platform/integrations/workflows-and-notifications/_category_.yml
  sources/platform/integrations/workflows-and-notifications/gmail.md
  sources/platform/integrations/workflows-and-notifications/make.md
  sources/platform/integrations/workflows-and-notifications/slack.md
  sources/platform/integrations/workflows-and-notifications/telegram.md
  sources/platform/integrations/workflows-and-notifications/zapier.md
  sources/platform/storage/dataset.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
  static/img/platform/integrations/pinecone.png
  static/img/platform/integrations/pinecone.svg
Labels: t-docs

#1051 docs: Update langchain code example to reflect changes in the langchain
  sources/platform/integrations/ai/langchain.md
Labels: t-ai

#1053 fix: Fixed menu item arrow position
  apify-docs-theme/src/theme/custom.css
Labels: bug, adhoc, t-web

#1059 docs: Fix broken link to flowise-apify-api.png for flowise integration doc
  sources/platform/integrations/ai/flowise.md
Labels: t-ai

#1043 docs: reworked links & prose to account for new landing pages
  sources/platform/actors/development/builds_and_runs/state_persistence.md
  sources/platform/actors/development/programming_interface/index.mdx
  sources/platform/proxy/google_serp_proxy.md
  sources/platform/proxy/index.md
  sources/platform/proxy/residential_proxy.md
  sources/platform/proxy/usage.md
  sources/platform/storage/dataset.md
  sources/platform/storage/index.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
  sources/platform/storage/usage.md
Labels: t-docs

#1020 fix: three small corrections in markup and code
  sources/academy/webscraping/advanced_web_scraping/tips_and_tricks_robustness.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/injecting_code.md
  sources/academy/webscraping/web_scraping_for_beginners/challenge/modularity.md
Labels: t-academy

#1027 style: use consistent code example language markers
  sources/academy/platform/deploying_your_code/index.md
  sources/academy/platform/deploying_your_code/inputs_outputs.md
  sources/academy/platform/getting_started/apify_client.md
  sources/academy/platform/getting_started/creating_actors.md
  sources/academy/tutorials/api/retry_failed_requests.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/apify_scrapers/puppeteer_scraper.md
  sources/academy/tutorials/node_js/avoid_eacces_error_in_actor_builds.md
  sources/academy/tutorials/node_js/multiple-runs-scrape.md
  sources/academy/tutorials/python/process_data_using_python.md
  sources/academy/tutorials/python/scrape_data_python.md
  sources/academy/webscraping/anti_scraping/mitigation/cloudflare_challenge.md
  sources/academy/webscraping/puppeteer_playwright/browser.md
  sources/academy/webscraping/puppeteer_playwright/browser_contexts.md
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/logging_into_a_website.md
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/extracting_data.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/index.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/injecting_code.md
  sources/academy/webscraping/puppeteer_playwright/page/index.md
  sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
  sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
  sources/academy/webscraping/puppeteer_playwright/page/waiting.md
  sources/academy/webscraping/puppeteer_playwright/proxies.md
  sources/academy/webscraping/puppeteer_playwright/reading_intercepting_requests.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/filtering_links.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/save_to_csv.md
Labels: t-academy

#1070 fix: silence eslint for new markdown snippets
  sources/academy/tutorials/node_js/multiple-runs-scrape.md
Labels: adhoc, t-tooling

#1067 fix(academy): capitalize 'actors' and 'actor'
  .github/styles/Apify/Capitalization.yml
  sources/academy/glossary/tools/apify_cli.md
  sources/academy/platform/apify_platform.md
  sources/academy/platform/deploying_your_code/deploying.md
  sources/academy/platform/deploying_your_code/docker_file.md
  sources/academy/platform/deploying_your_code/index.md
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/academy/platform/deploying_your_code/inputs_outputs.md
  sources/academy/platform/deploying_your_code/output_schema.md
  sources/academy/platform/expert_scraping_with_apify/actors_webhooks.md
  sources/academy/platform/expert_scraping_with_apify/apify_api_and_client.md
  sources/academy/platform/expert_scraping_with_apify/bypassing_anti_scraping.md
  sources/academy/platform/expert_scraping_with_apify/index.md
  sources/academy/platform/expert_scraping_with_apify/managing_source_code.md
  sources/academy/platform/expert_scraping_with_apify/migrations_maintaining_state.md
  sources/academy/platform/expert_scraping_with_apify/saving_useful_stats.md
  sources/academy/platform/expert_scraping_with_apify/solutions/handling_migrations.md
  sources/academy/platform/expert_scraping_with_apify/solutions/integrating_webhooks.md
  sources/academy/platform/expert_scraping_with_apify/solutions/managing_source.md
  sources/academy/platform/expert_scraping_with_apify/solutions/rotating_proxies.md
  sources/academy/platform/expert_scraping_with_apify/solutions/saving_stats.md
  sources/academy/platform/expert_scraping_with_apify/solutions/using_api_and_client.md
  sources/academy/platform/expert_scraping_with_apify/solutions/using_storage_creating_tasks.md
  sources/academy/platform/expert_scraping_with_apify/tasks_and_storage.md
  sources/academy/platform/get_most_of_actors/index.md
  sources/academy/platform/get_most_of_actors/naming_your_actor.md
  sources/academy/platform/get_most_of_actors/seo_and_promotion.md
  sources/academy/platform/getting_started/actors.md
  sources/academy/platform/getting_started/apify_api.md
  sources/academy/platform/getting_started/apify_client.md
  sources/academy/platform/getting_started/creating_actors.md
  sources/academy/platform/getting_started/index.md
  sources/academy/platform/getting_started/inputs_outputs.md
  sources/academy/platform/running_a_web_server.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/apify_scrapers/cheerio_scraper.md
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/academy/tutorials/apify_scrapers/index.md
  sources/academy/tutorials/apify_scrapers/puppeteer_scraper.md
  sources/academy/tutorials/apify_scrapers/web_scraper.md
  sources/academy/tutorials/node_js/avoid_eacces_error_in_actor_builds.md
  sources/academy/tutorials/node_js/filter_blocked_requests_using_sessions.md
  sources/academy/tutorials/node_js/how_to_save_screenshots_puppeteer.md
  sources/academy/tutorials/node_js/request_labels_in_apify_actors.md
  sources/academy/tutorials/node_js/scraping_from_sitemaps.md
  sources/academy/tutorials/node_js/scraping_urls_list_from_google_sheets.md
  sources/academy/tutorials/node_js/submitting_form_with_file_attachment.md
  sources/academy/tutorials/node_js/when_to_use_puppeteer_scraper.md
  sources/academy/tutorials/php/using_apify_from_php.md
  sources/academy/tutorials/python/process_data_using_python.md
  sources/academy/tutorials/python/scrape_data_python.md
  sources/academy/webscraping/anti_scraping/techniques/captchas.md
  sources/academy/webscraping/puppeteer_playwright/proxies.md
  sources/academy/webscraping/web_scraping_for_beginners/challenge/index.md
Labels: t-academy

#1074 docs: add new admonition to index.md within integrations/actors
  sources/platform/integrations/actors/index.md
Labels: t-docs

#1072 docs: update examples for pinecone integration (because of the new actor)
  sources/platform/integrations/ai/pinecone.md
  sources/platform/integrations/images/pinecone-integration-setup.png
Labels: t-ai

#1073 fix: fine-tune Vale and fix all outstanding errors
  .github/styles/Apify/Capitalization.yml
  sources/academy/glossary/concepts/index.md
  sources/academy/platform/expert_scraping_with_apify/index.md
  sources/academy/platform/expert_scraping_with_apify/solutions/saving_stats.md
  sources/academy/platform/get_most_of_actors/index.md
  sources/academy/platform/get_most_of_actors/naming_your_actor.md
  sources/academy/tutorials/api/retry_failed_requests.md
  sources/academy/tutorials/node_js/analyzing_pages_and_fixing_errors.md
  sources/academy/tutorials/node_js/dealing_with_dynamic_pages.md
  sources/academy/tutorials/node_js/js_in_html.md
  sources/academy/tutorials/node_js/processing_multiple_pages_web_scraper.md
  sources/academy/tutorials/node_js/request_labels_in_apify_actors.md
  sources/academy/tutorials/node_js/scraping_shadow_doms.md
  sources/academy/webscraping/anti_scraping/mitigation/proxies.md
  sources/academy/webscraping/anti_scraping/techniques/captchas.md
  sources/academy/webscraping/anti_scraping/techniques/rate_limiting.md
  sources/academy/webscraping/puppeteer_playwright/browser.md
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/index.md
  sources/academy/webscraping/puppeteer_playwright/index.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/finding_links.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/first_crawl.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/headless_browser.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/index.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/save_to_csv.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/using_devtools.md
  sources/academy/webscraping/scraping_basics_javascript/introduction.md
  sources/platform/actors/development/builds_and_runs/state_persistence.md
  sources/platform/actors/development/deployment/automated_tests.md
  sources/platform/actors/development/deployment/index.md
  sources/platform/actors/development/performance.md
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/actors/development/programming_interface/metamorph.md
  sources/platform/actors/development/quick_start/index.mdx
  sources/platform/actors/development/quick_start/start_locally.md
  sources/platform/actors/development/quick_start/start_web_ide.md
  sources/platform/actors/publishing/index.mdx
  sources/platform/actors/publishing/publish.mdx
  sources/platform/actors/running/index.md
  sources/platform/actors/running/usage_and_resources.md
  sources/platform/collaboration/index.md
  sources/platform/collaboration/organization_account/how_to_use.md
  sources/platform/console/billing.md
  sources/platform/integrations/integrate_with_apify.md
  sources/platform/integrations/programming/webhooks/actions.md
  sources/platform/monitoring/index.md
  sources/platform/proxy/datacenter_proxy.md
  sources/platform/storage/usage.md
  vale.ini
Labels: t-academy, t-docs

#1077 docs: Add documentation for Qdrant integration
  sources/platform/integrations/ai/qdrant.md
  sources/platform/integrations/images/qdrant-integration-setup.png
  sources/platform/integrations/images/qdrant-wcc-integration-connect.png
  sources/platform/integrations/images/qdrant-wcc-integration.png
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/qdrant.svg
Labels: t-ai

#1084 fix: use white github icon for dark theme
  package-lock.json
  sources/platform/integrations/index.mdx
  src/components/Card.jsx
  static/img/platform/integrations/github-white.svg
Labels: t-web

#1085 feat: remove background from hero section
  src/components/Hero/styles.module.css
  src/pages/api/index.tsx
  src/pages/img/hero-background-gradient.svg
  src/pages/sdk/index.tsx
  static/img/hero_background.svg
Labels: t-web
