Repository apify/apify-docs, pull requests merged in 2024-07, with the labels that each got.

#1079 feat: add API documentation for dataset validation
  sources/platform/api_v2/api_v2_reference.apib
Labels: documentation, adhoc, t-console, product roadmap

#1088 feat(ci): Add redirects for Crawlee to `nginx.conf`
  nginx.conf
Labels: adhoc, t-platform

#1089 feat: Adjust `nginx.conf` so that `crawlee.dev/python` can load assets
  nginx.conf
Labels: adhoc, t-platform

#1081 feat: update input schema docs
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-options.png
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-console

#1091 feat: publish the new openapi docs on `/api/v2` and move apiary docs to `/api/v2-old`
  apify-docs-theme/src/theme/custom.css
  docusaurus.config.js
  package-lock.json
  src/pages/api/v2-old.js
Labels: adhoc, t-tooling

#1086 feat: add Actor Standby documentation
  sources/platform/actors/running/actor_standby.md
  sources/platform/actors/running/images/actor_standby/standby-creators.png
  sources/platform/actors/running/images/actor_standby/standby-tab.png
Labels: t-c&c

#1093 fix: hide redocusaurus sidebar footer + expand all responses
  .redocly.yaml
  apify-docs-theme/src/theme/custom.css
  package-lock.json
Labels: adhoc, t-tooling

#1092 chore: update Actor Standby code examples
  sources/platform/actors/running/actor_standby.md
Labels: adhoc, t-platform

#1094 fix: disallow old api docs from indexing
  static/robots.txt
Labels: adhoc, t-tooling

#1096 feat: improve standby docs
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/actors/development/programming_interface/images/standby-creators.png
  sources/platform/actors/development/programming_interface/index.mdx
  sources/platform/actors/running/actor_standby.md
Labels: adhoc, t-platform

#1098 fix: make standby headings h2
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/running/actor_standby.md
Labels: adhoc, t-platform

#1099 fix: missing pagination image
  sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
  sources/academy/webscraping/api_scraping/general_api_scraping/images/pagination.png
Labels: t-academy

#1103 fix: rewrite the P&P course intro
  sources/academy/webscraping/puppeteer_playwright/index.md
Labels: t-academy

#1106 fix: remove newsletter mention
  sources/academy/webscraping/anti_scraping/mitigation/generating_fingerprints.md
Labels: t-academy

#1105 feat: open source landing page
  apify-docs-theme/src/config.js
  package-lock.json
  package.json
  src/components/ActionCard/ActionCard.tsx
  src/components/Button.tsx
  src/components/CardWithImageAndContent/ImageWithContent.tsx
  src/components/Heading.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/styles.module.css
  src/components/Section/Section.tsx
  src/components/Section/styles.module.css
  src/components/Tabs.tsx
  src/pages/api/index.tsx
  src/pages/index.tsx
  src/pages/open-source/index.tsx
  src/pages/sdk/index.tsx
  static/img/fingerprint-suite.svg
  static/img/got-scraping.svg
Labels: t-web

#1112 fix: remove cli image dimensions in landing page
  src/pages/index.tsx
Labels: t-web

#1111 feat: minor actor standby improvements
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/running/actor_standby.md
Labels: t-platform

#1113 docs: Improve description for vector database integrations
  sources/platform/integrations/ai/pinecone.md
  sources/platform/integrations/ai/qdrant.md
  sources/platform/integrations/images/pinecone-create-index.png
  sources/platform/integrations/images/pinecone-integration-setup.png
  sources/platform/integrations/images/pinecone-wcc-integration.png
  sources/platform/integrations/images/qdrant-integration-setup.png
  sources/platform/integrations/images/qdrant-wcc-integration-connect.png
  sources/platform/integrations/images/qdrant-wcc-integration.png
Labels: t-ai

#1114 fix: mention enabling ESM support
  sources/academy/webscraping/scraping_basics_javascript/crawling/pro_scraping.md
Labels: adhoc, t-tooling

#1082 docs: rewrite performance docs
  sources/platform/actors/development/actor_definition/docker.md
  sources/platform/actors/development/performance.md
Labels: t-docs

#1126 chore: typo fixes, proxy IP availability
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
  sources/platform/actors/development/quick_start/start_locally.md
  sources/platform/index.mdx
  sources/platform/proxy/usage.md
Labels: adhoc, t-docs

#1127 fix: remove hero section gradient
  src/components/Hero/styles.module.css
Labels: bug, adhoc, t-web

#1117 feat: make pay-per-result pricing explicit
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
Labels: t-c&c
