Repository apify/apify-docs, pull requests merged in 2024-05, with the labels that each got.

#994 docs: fix typos in request queue limits description
  sources/platform/storage/request_queue.md
Labels: t-ai

#991 docs: Add API Clients landing page
  apify-docs-theme/src/config.js
  nginx.conf
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/GitButton.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/styles.module.css
  src/components/Section/Section.tsx
  src/components/Tabs.tsx
  src/components/UiLibraryWrapper.tsx
  src/pages/api/index.tsx
  src/pages/api/styles.module.css
  static/img/hero_background.svg
  static/img/javascript-40x40.svg
  static/img/python-40x40.svg
Labels: t-web

#996 docs: fix example URLs in the actor monorepos (plus some minor changes)
  sources/platform/actors/development/deployment/source_types.md
  sources/platform/integrations/langchain.md
Labels: t-ai

#998 docs: fix link to langchain docs
  sources/platform/integrations/langchain.md
Labels: t-docs

#995 docs: Add SDK landing page
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  apify-docs-theme/src/theme/NavbarItem/NavbarNavLink.jsx
  apify-docs-theme/static/img/javascript-40x40.svg
  apify-docs-theme/static/img/python-40x40.svg
  nginx.conf
  src/components/Button.tsx
  src/components/Hero/styles.module.css
  src/components/SdkSection/SdkSection.tsx
  src/components/Section/Section.tsx
  src/pages/api/index.tsx
  src/pages/api/styles.module.css
  src/pages/sdk/index.tsx
Labels: t-web

#990 feat: improve monetization docs
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  sources/platform/actors/publishing/testing.mdx
Labels: t-c&c, tested

#933 docs: update web ide doc
  sources/platform/actors/development/quick_start/images/actor-build.png
  sources/platform/actors/development/quick_start/images/actor-create-button.png
  sources/platform/actors/development/quick_start/images/actor-create-templates.png
  sources/platform/actors/development/quick_start/images/actor-input.png
  sources/platform/actors/development/quick_start/images/actor-run.png
  sources/platform/actors/development/quick_start/images/actor-source-code.png
  sources/platform/actors/development/quick_start/start_web_ide.md
Labels: t-docs

#931 docs: rewrite local development section
  sources/platform/actors/development/quick_start/images/actor-create.gif
  sources/platform/actors/development/quick_start/start_locally.md
Labels: t-docs

#1005 fix(request-queue): remove concurrency limit
  sources/platform/storage/request_queue.md
Labels: adhoc, t-platform

#1002 docs: updates to input schema section
  sources/platform/actors/development/actor_definition/input_schema/index.md
  sources/platform/actors/development/actor_definition/input_schema/secret_input.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: t-docs

#1006 fix(docs): codeblock correct theme
  package-lock.json
  src/components/UiLibraryWrapper.tsx
Labels: adhoc, t-web

#943 refactor: link to MDN as a canonical resource
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/filtering_links.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/browser_devtools.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/index.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
  sources/academy/webscraping/web_scraping_for_beginners/index.md
Labels: t-academy

#1013 feat: embed video
  sources/academy/webscraping/anti_scraping/index.md
Labels: t-academy

#1021 fix(academy): remove unnecessary exclamation mark
  sources/academy/webscraping/switching_to_typescript/installation.md
Labels: t-academy

#1019 feat: follow the best practice
  sources/academy/webscraping/puppeteer_playwright/executing_scripts/index.md
Labels: t-academy

#1017 fix: rename several chapters to improve orientation and fix a few small issues
  sources/academy/tutorials/python/process_data_using_python.md
  sources/academy/webscraping/advanced_web_scraping/scraping_paginated_sites.md
  sources/academy/webscraping/web_scraping_for_beginners/challenge/scraping_amazon.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/browser_devtools.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/devtools_continued.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_continued.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
Labels: t-academy

#1018 fix: mention the video is outdated, but explain it's still valuable
  sources/academy/webscraping/anti_scraping/index.md
Labels: t-academy

#1011 fix: improve stylistics and several explanations
  sources/academy/webscraping/web_scraping_for_beginners/crawling/headless_browser.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/index.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/pro_scraping.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
  sources/academy/webscraping/web_scraping_for_beginners/introduction.md
Labels: t-academy

#1010 fix: spelling of several terms
  sources/academy/glossary/concepts/dynamic_pages.md
  sources/academy/glossary/tools/apify_cli.md
  sources/academy/glossary/tools/quick_javascript_switcher.md
  sources/academy/glossary/tools/user_agent_switcher.md
  sources/academy/platform/deploying_your_code/docker_file.md
  sources/academy/platform/expert_scraping_with_apify/apify_api_and_client.md
  sources/academy/platform/expert_scraping_with_apify/solutions/using_api_and_client.md
  sources/academy/platform/getting_started/apify_client.md
  sources/academy/tutorials/node_js/choosing_the_right_scraper.md
  sources/academy/webscraping/anti_scraping/index.md
  sources/academy/webscraping/anti_scraping/mitigation/generating_fingerprints.md
  sources/academy/webscraping/anti_scraping/mitigation/using_proxies.md
  sources/academy/webscraping/anti_scraping/techniques/browser_challenges.md
  sources/academy/webscraping/api_scraping/graphql_scraping/custom_queries.md
  sources/academy/webscraping/switching_to_typescript/index.md
  sources/academy/webscraping/switching_to_typescript/installation.md
  sources/academy/webscraping/web_scraping_for_beginners/crawling/pro_scraping.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/computer_preparation.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/project_setup.md
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/save_to_csv.md
Labels: t-academy

#1029 docs: correct LlamaIndex examples
  sources/platform/integrations/llama.md
Labels: t-ai

#1034 docs: add Pinecone integration section
  sources/platform/integrations/images/pinecone-integration-setup.png
  sources/platform/integrations/images/pinecone-wcc-integration.png
  sources/platform/integrations/index.mdx
  sources/platform/integrations/llama.md
  sources/platform/integrations/pinecone.md
  static/img/platform/integrations/pinecone.png
Labels: t-ai

#1032 docs: updates to source code doc
  sources/platform/actors/development/actor_definition/source_code.md
Labels: t-docs

#1024 docs: update output schema document
  sources/platform/actors/development/actor_definition/output_schema.md
Labels: documentation, t-docs

#1031 docs: Dockerfile doc improvements & rewrites
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/docker.md
  sources/platform/actors/development/actor_definition/dockerfile.md
  sources/platform/actors/development/actor_definition/index.md
  sources/platform/actors/development/actor_definition/source_code.md
  sources/platform/actors/development/deployment/source_types.md
  sources/platform/actors/development/performance.md
Labels: t-docs

#1035 feat: add new openapi specs with redocusaurus
  .lycheeignore
  docusaurus.config.js
  package-lock.json
  package.json
  static/robots.txt
Labels: adhoc, t-tooling

#1036 docs: Added redirects for removed api clients pages
  nginx.conf
Labels: bug, adhoc, t-web

#1037 fix: split the `@font-face` rule to make it valid
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#1038 fix: don't replace all the fonts with Lota Grotesque SemiBold
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#1039 fix: always use latest openapi from npm
  .github/workflows/docs.yaml
  .github/workflows/lychee.yml
  .lycheeignore
  .redocly.yaml
  docusaurus.config.js
  package-lock.json
  package.json
  sources/platform/api_v2/api_v2_reference.apib
  src/theme/DocItem/Layout/index.js
Labels: adhoc, t-tooling
