Repository apify/apify-docs, pull requests merged in 2024-04, with the labels that each got.

#912 chore: update ui components
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#915 feat: Adding missing integrations and info for people integrating their services with Apify
  nginx.conf
  sources/platform/integrations/chatgpt.md
  sources/platform/integrations/images/airbyte-sources-web.png
  sources/platform/integrations/images/integration-ready-actors.png
  sources/platform/integrations/index.mdx
  sources/platform/integrations/integrate_with_apify.md
  static/img/platform/integrations/flowise.png
  static/img/platform/integrations/llamaindex.jpeg
  static/img/platform/integrations/telegram.svg
Labels: adhoc, t-platform

#904 feat(request-queue): Extend rq documentation with rqv2 features
  sources/platform/storage/request_queue.md
Labels: t-platform

#916 docs: Keboola integration doc
  sources/platform/integrations/images/keboola/keboola-component-setup.png
  sources/platform/integrations/images/keboola/keboola-components.png
  sources/platform/integrations/images/keboola/keboola-configure-component.png
  sources/platform/integrations/images/keboola/keboola-connector.png
  sources/platform/integrations/images/keboola/keboola-create-configuration.png
  sources/platform/integrations/images/keboola/keboola-dashboard.png
  sources/platform/integrations/images/keboola/keboola-run-component.png
  sources/platform/integrations/images/keboola/keboola-setup-api-token.png
  sources/platform/integrations/images/keboola/keboola-setup-specification.png
  sources/platform/integrations/integrate_with_apify.md
  sources/platform/integrations/keboola.md
Labels: t-docs

#919 docs: Update keboola.md
  sources/platform/integrations/keboola.md
Labels: t-docs

#921 fix: Flowise icon
  sources/platform/integrations/index.mdx
Labels: adhoc, t-platform

#920 docs: add usage overage info
  sources/platform/console/billing.md
  sources/platform/limits.md
Labels: t-docs

#929 docs: add info about plan add-ons
  sources/platform/console/billing.md
Labels: t-docs

#934 docs: update langchain integration docs as the Document has moved to langchain_core
  sources/platform/integrations/langchain.md
Labels: t-ai

#935 feat: Improve Apify Proxy Usage docs
  sources/platform/proxy/usage.md
Labels: t-platform

#918 feat: Added tutorial to scraper website from multiple Actor runs
  .eslintrc.json
  examples/ts-parallel-scraping/orchestrator/.actor/Dockerfile
  examples/ts-parallel-scraping/orchestrator/.actor/actor.json
  examples/ts-parallel-scraping/orchestrator/.actor/input_schema.json
  examples/ts-parallel-scraping/orchestrator/package.json
  examples/ts-parallel-scraping/orchestrator/src/main.ts
  examples/ts-parallel-scraping/orchestrator/tsconfig.json
  examples/ts-parallel-scraping/scraper/.actor/Dockerfile
  examples/ts-parallel-scraping/scraper/.actor/actor.json
  examples/ts-parallel-scraping/scraper/.actor/input_schema.json
  examples/ts-parallel-scraping/scraper/package.json
  examples/ts-parallel-scraping/scraper/src/main.ts
  examples/ts-parallel-scraping/scraper/tsconfig.json
  sources/academy/tutorials/node_js/images/orchestrator-actor-input.png
  sources/academy/tutorials/node_js/images/orchestrator-actor.png
  sources/academy/tutorials/node_js/images/scraper-actor-runs.png
  sources/academy/tutorials/node_js/images/scraper-actor.png
  sources/academy/tutorials/node_js/multiple-runs-scrape.md
  sources/platform/storage/request_queue.md
Labels: t-platform

#939 feat: moved imports of all shared components to ui-library
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/ActionCard/ActionCard.tsx
  src/components/ActorTemplates/ActorTemplates.tsx
  src/components/Button.tsx
  src/components/CardWithIcon/CardWithIcon.tsx
  src/components/Heading.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/PlainCard/PlainCard.tsx
  src/components/Section/Section.tsx
  src/components/Text.tsx
  src/pages/index.tsx
Labels: t-web

#945 feat: update organizations section, plus some misc things
  sources/platform/collaboration/images/organizations/configure-permissions.png
  sources/platform/collaboration/images/organizations/convert-to-organization.png
  sources/platform/collaboration/images/organizations/integrations.png
  sources/platform/collaboration/images/organizations/members.png
  sources/platform/collaboration/images/organizations/my-organizations.png
  sources/platform/collaboration/images/organizations/roles.png
  sources/platform/collaboration/images/organizations/switch-to-organization.png
  sources/platform/collaboration/images/organizations/upgrade.png
  sources/platform/collaboration/organization_account/how_to_use.md
  sources/platform/collaboration/organization_account/index.md
  sources/platform/collaboration/organization_account/setup.md
  sources/platform/monitoring/index.md
  sources/platform/schedules.md
Labels: documentation, adhoc, debt, t-console

#989 docs: fix typo in dataset.md
  sources/platform/storage/dataset.md
Labels: t-docs
