Repository apify/apify-docs, pull requests merged in 2024-08, with the labels that each got.

#1133 feat: Add haystack integration
  sources/platform/integrations/ai/haystack.md
Labels: t-ai

#1132 docs: add visibility to keyboard shortcuts
  sources/platform/console/index.md
Labels: t-docs

#1121 docs: improve system events doc
  sources/platform/actors/development/programming_interface/system_events.md
Labels: t-docs

#1120 docs: improve status message doc
  sources/platform/actors/development/programming_interface/status_messages.md
Labels: t-docs

#1118 docs: improve basic commands document
  sources/platform/actors/development/programming_interface/basic_commands.md
Labels: t-docs

#1123 docs: improve metamorph section
  sources/platform/actors/development/programming_interface/metamorph.md
Labels: t-docs

#1122 docs: improve container web server doc
  sources/platform/actors/development/programming_interface/container_web_server.md
Labels: t-docs

#1140 feat: change link checking to periodic
  .github/workflows/lychee.yml
Labels: t-docs

#1143 fix: remove output arg from lychee workflow
  .github/workflows/lychee.yml
Labels: t-docs

#1124 docs: improve environment variables section
  sources/platform/actors/development/programming_interface/environment_variables.md
  vale.ini
Labels: t-docs

#1146 chore: bump search modal version
  apify-docs-theme/package.json
  package-lock.json
Labels: adhoc, t-tooling

#1150 feat: Improve Standby docs
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/development/programming_interface/container_web_server.md
  sources/platform/actors/running/runs_and_builds.md
Labels: t-platform

#1158 docs(platform): update run data retention info
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/platform/actors/running/runs_and_builds.md
  sources/platform/storage/usage.md
Labels: adhoc, t-console

#1165 docs: rename ouptut schema to dataset schema
  nginx.conf
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/academy/platform/deploying_your_code/output_schema.md
  sources/academy/webscraping/api_scraping/graphql_scraping/custom_queries.md
  sources/academy/webscraping/api_scraping/index.md
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/index.md
  sources/platform/actors/development/actor_definition/output_schema.md
Labels: t-docs

#1153 feat(UI): make h2 default section heading
  src/components/Section/Section.tsx
  src/pages/api/index.tsx
Labels: bug, documentation, adhoc, t-c&c

#1159 fix: fav icons
  apify-docs-theme/static/img/favicon.ico
  docusaurus.config.js
Labels: adhoc, t-web

#1168 docs: fix typo in Actor Stanby
  sources/platform/actors/running/actor_standby.md
Labels: t-docs

#1157 fix: Update main.py
  examples/python-data-scraper/main.py
Labels: documentation, t-tooling

#1169 docs: fix typo in nginx.conf
  nginx.conf
Labels: t-docs

#1170 fix: Fix mobile screen issues
  apify-docs-theme/src/theme/custom.css
Labels: t-web

#1171 docs: Fix typo in Environment variables page
  sources/platform/actors/development/programming_interface/environment_variables.md
Labels: adhoc, t-tooling

#1166 docs: fix outdated information relating to Actor insights
  sources/academy/platform/get_most_of_actors/images/actor-insights.png
  sources/academy/platform/get_most_of_actors/images/monetization-section.png
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
Labels: t-docs

#1142 fix: Update store.md
  sources/platform/actors/running/store.md
Labels: t-docs

#1167 docs: fix outdated docs re: create new actor button
  sources/academy/platform/deploying_your_code/deploying.md
  sources/academy/platform/getting_started/creating_actors.md
  sources/academy/platform/getting_started/images/develop-new-actor.png
  sources/academy/tutorials/python/scrape_data_python.md
Labels: t-docs
