Repository apify/apify-docs, pull requests merged in 2024-02, with the labels that each got.

#846 docs: Added console authentication docs
  sources/platform/console/images/console-account-two-factor-disabled.png
  sources/platform/console/images/console-account-two-factor-enabled.png
  sources/platform/console/images/console-email-verification-page.png
  sources/platform/console/images/console-forgotten-password-page.png
  sources/platform/console/images/console-reset-password-page.png
  sources/platform/console/images/console-setup-two-factor-auth-key.png
  sources/platform/console/images/console-sign-in-form.png
  sources/platform/console/images/console-sign-in-methods-section.png
  sources/platform/console/images/console-sign-up-form.png
  sources/platform/console/images/console-two-factor-app-setup.png
  sources/platform/console/images/console-two-factor-auth-disable.png
  sources/platform/console/images/console-two-factor-authentication.png
  sources/platform/console/images/console-two-factor-recovery-settings-request.png
  sources/platform/console/images/console-two-factor-recovery-settings-revealed.png
  sources/platform/console/images/console-two-factor-recovery-setup.png
  sources/platform/console/images/console-two-factor-use-recovery-code.png
  sources/platform/console/index.md
  sources/platform/console/two-factor-authentication.md
Labels: documentation, t-console

#858 fix: improve contrast on inline code blocks and footer links
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#852 docs(api): update reference for log endpoints, including the new ones for build
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#854 docs: fix code sample in academy
  sources/academy/webscraping/web_scraping_for_beginners/data_extraction/project_setup.md
Labels: t-docs

#857 docs: (even more) explicitly mention Apiary when updating API reference
  CONTRIBUTING.md
Labels: adhoc, t-platform

#859 docs(api): mark run and build endpoints under /acts/:actor_id deprecated
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#861 chore: update eslint to check codeblocks in all markdown files
  .eslintrc.json
  CONTRIBUTING.md
  apify-docs-theme/package.json
  apify-docs-theme/src/roa-loader/index.js
  apify-docs-theme/src/theme.js
  apify-docs-theme/src/theme/DocBreadcrumbs/Items/Home/index.js
  apify-docs-theme/src/theme/DocBreadcrumbs/index.js
  apify-docs-theme/src/theme/Footer/LinkItem/index.js
  apify-docs-theme/src/theme/Logo/index.js
  apify-docs-theme/src/theme/MDXComponents/Code.js
  apify-docs-theme/src/theme/MDXComponents/Details.js
  apify-docs-theme/src/theme/MDXComponents/Head.js
  apify-docs-theme/src/theme/MDXComponents/Heading.js
  apify-docs-theme/src/theme/MDXComponents/Img/index.js
  apify-docs-theme/src/theme/MDXComponents/Pre.js
  apify-docs-theme/src/theme/MDXComponents/Ul/index.js
  apify-docs-theme/src/theme/MDXComponents/index.js
  apify-docs-theme/src/theme/SearchBar/index.js
  apify-docs-theme/src/theme/SearchMetadata/index.js
  docusaurus.config.js
  package-lock.json
  package.json
  sources/academy/.eslintrc.json
  sources/academy/platform/getting_started/creating_actors.md
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/input_schema/index.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
  sources/platform/actors/development/actor_definition/output_schema.md
  sources/platform/actors/development/deployment/automated_tests.md
  sources/platform/actors/development/programming_interface/basic_commands.md
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/actors/development/programming_interface/system_events.md
  sources/platform/integrations/actors/integrating_actors_via_api.md
  sources/platform/integrations/webhooks/actions.md
  sources/platform/integrations/webhooks/events.md
  sources/platform/proxy/datacenter_proxy.md
  sources/platform/proxy/google_serp_proxy.md
  sources/platform/proxy/index.md
  sources/platform/storage/dataset.md
  src/components/ActionCard/ActionCard.tsx
  src/components/ActorTemplates/ActorTemplates.tsx
  src/components/Button.tsx
  src/components/CardWithIcon/CardWithIcon.tsx
  src/components/CardWithImageAndContent/ImageWithContent.tsx
  src/components/ChangeLog/ChangeLog.tsx
  src/components/Heading.tsx
  src/components/Hero/Hero.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/PlainCard/PlainCard.tsx
  src/components/Section/Section.tsx
  src/components/Text.tsx
  src/pages/api/v2.js
  src/pages/index.tsx
  src/pages/versions.js
  src/theme/DocItem/Layout/index.js
  src/theme/DocItem/Metadata/index.js
Labels: adhoc, t-tooling, tested

#853 docs: add images & write gmail & gdrive integration
  sources/platform/integrations/drive.md
  sources/platform/integrations/gmail.md
  sources/platform/integrations/images/gdrive/google-maps-task-add-google-drive-integration.png
  sources/platform/integrations/images/gdrive/google-maps-task-integration-format.png
  sources/platform/integrations/images/gdrive/google-maps-task-integration-save.png
  sources/platform/integrations/images/gdrive/google-maps-task-integration-setup.png
  sources/platform/integrations/images/gdrive/google-maps-task-integrations.png
  sources/platform/integrations/images/gmail/google-maps-task-configuration.png
  sources/platform/integrations/images/gmail/google-maps-task-email-filled.png
  sources/platform/integrations/images/gmail/google-maps-task-email-format.png
  sources/platform/integrations/images/gmail/google-maps-task-email-save.png
  sources/platform/integrations/images/gmail/google-maps-task-email.png
  sources/platform/integrations/images/gmail/google-maps-task-integrations.png
  sources/platform/integrations/telegram.md
Labels: t-docs

#865 docs: remove dead link
  sources/academy/webscraping/anti_scraping/mitigation/cloudflare_challenge.md
  vale.ini
Labels: t-docs

#867 fix: ensure `external/const/static` badges in API docs are readable
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#868 docs: update MonthlyUsage and AccountLimits in API reference
  sources/platform/api_v2/api_v2_reference.apib
Labels: t-platform

#872 docs: rewrite + fixes for Vale & mdlint
  sources/academy/tutorials/node_js/block_requests_puppeteer.md
Labels: t-docs

#873 feat: add line numbers to code examples via CSS globally
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#874 docs: changes to style guide
  README.md
Labels: t-docs
