Repository apify/apify-docs, pull requests merged in 2024-10, with the labels that each got.

#1205 feat: Python course lesson about saving data
  _typos.toml
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/images/csv-example.png
  sources/academy/webscraping/scraping_basics_python/images/csv-sheets.png
  sources/academy/webscraping/scraping_basics_python/images/csv.png
  sources/academy/webscraping/scraping_basics_python/index.md
Labels: t-academy

#1211 docs: add storages editor to input schema specification
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, t-console

#1232 docs: revert storages editor input
  sources/platform/actors/development/actor_definition/input_schema/specification.md
  sources/platform/storage/dataset.md
Labels: documentation, adhoc, t-console

#1231 feat: Update set up for Milvus database and add link to RAG notebook.
  sources/platform/integrations/ai/milvus.md
Labels: t-ai

#1190 chore: throw on build with broken anchors
  docusaurus.config.js
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/academy/platform/expert_scraping_with_apify/bypassing_anti_scraping.md
  sources/academy/platform/expert_scraping_with_apify/solutions/handling_migrations.md
  sources/academy/platform/expert_scraping_with_apify/tasks_and_storage.md
  sources/academy/platform/getting_started/inputs_outputs.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/apify_scrapers/cheerio_scraper.md
  sources/academy/tutorials/apify_scrapers/getting_started.md
  sources/academy/tutorials/apify_scrapers/index.md
  sources/academy/tutorials/apify_scrapers/puppeteer_scraper.md
  sources/academy/tutorials/apify_scrapers/web_scraper.md
  sources/academy/tutorials/node_js/analyzing_pages_and_fixing_errors.md
  sources/academy/tutorials/node_js/filter_blocked_requests_using_sessions.md
  sources/academy/tutorials/php/using_apify_from_php.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/using_devtools.md
  sources/platform/actors/development/builds_and_runs/builds.md
  sources/platform/actors/development/builds_and_runs/index.md
  sources/platform/actors/development/builds_and_runs/state_persistence.md
  sources/platform/actors/development/programming_interface/basic_commands.md
  sources/platform/integrations/index.mdx
  sources/platform/integrations/workflows-and-notifications/make.md
  sources/platform/proxy/datacenter_proxy.md
  sources/platform/proxy/index.md
  sources/platform/proxy/usage.md
  sources/platform/storage/dataset.md
  sources/platform/storage/index.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
Labels: t-tooling

#1242 feat: add standby URL, changes to port unification
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/development/programming_interface/environment_variables.md
Labels: t-platform

#1239 docs: rewrite runs section
  sources/platform/actors/development/builds_and_runs/runs.md
Labels: t-docs

#1237 docs: rewrite state persistence
  sources/platform/actors/development/builds_and_runs/state_persistence.md
Labels: t-docs

#1245 docs: Add open assistants integration
  sources/platform/integrations/ai/openai_assistants.md
  sources/platform/integrations/images/openai-assistant-rag-web-browser.png
  sources/platform/integrations/images/openai-vector-store-integration.png
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/openai-white.svg
  static/img/platform/integrations/openai.svg
Labels: t-ai

#1214 feat: Python course lesson about getting links
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/images/refactoring.gif
Labels: t-academy

#1248 docs: Remove openai assistant id, simplify code by removing typing
  sources/platform/integrations/ai/openai_assistants.md
Labels: t-ai

#1235 docs: added dpa
  sources/legal/latest/terms/data-processing-addendum.md
Labels: t-docs

#1253 fix: fix content width on pages without much content
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#1255 chore: mention the new API docs in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: adhoc, t-tooling

#1257 docs: change link checker behaviour
  .github/workflows/lychee.yml
Labels: t-docs

#1256 feat: add initial PPE documentation
  sources/platform/actors/running/images/store/pay_per_event_example_actor.png
  sources/platform/actors/running/images/store/pay_per_event_historical_usage_tab.png
  sources/platform/actors/running/images/store/pay_per_event_max_charge_per_run.png
  sources/platform/actors/running/images/store/pay_per_event_price_on_run_detail.png
  sources/platform/actors/running/store.md
Labels: t-c&c

#1258 docs: add info regarding development section
  sources/academy/platform/deploying_your_code/deploying.md
  sources/academy/platform/getting_started/creating_actors.md
  sources/academy/platform/getting_started/images/develop-new-actor.png
  sources/academy/tutorials/python/scrape_data_python.md
  sources/platform/actors/development/quick_start/images/actor-create-button.png
  sources/platform/actors/development/quick_start/start_web_ide.md
  sources/platform/console/index.md
Labels: t-docs

#1259 docs: update requestListSources input screenshot
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-start-urls.png
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, adhoc, t-console

#1222 fix: landing pages syntax highlighting [internal]
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/CodeThemes/dark.js
  apify-docs-theme/src/theme/CodeThemes/light.js
  apify-docs-theme/src/theme/custom.css
  src/components/SdkSection/SdkSection.tsx
  src/pages/api/index.tsx
Labels: adhoc, medium priority, t-web

#1268 ci: Fix python docs build
  .github/workflows/publish-theme.yaml
Labels: adhoc, t-tooling
