Repository apify/apify-docs, pull requests merged in 2024-11, with the labels that each got.

#1271 feat: change behaviour of lychee link checker
  .github/workflows/lychee.yml
Labels: t-docs

#1272 feat: change lychee link checker to fail on error
  .github/workflows/lychee.yml
Labels: t-docs

#1273 chore: add redirect for crawlee-python upgrading page
  nginx.conf
Labels: adhoc, t-tooling

#1274 docs: Update LangChain integration to remove wrong links
  sources/platform/integrations/ai/langchain.md
Labels: t-ai

#1282 fix: Add a paragraph about authentication to Actor Standby
  sources/platform/actors/running/actor_standby.md
Labels: adhoc, t-platform

#1288 feat: scroll api docs sidebar automatically into current viewport
  apify-docs-theme/static/js/custom.js
Labels: adhoc, t-tooling

#1278 docs: restructure content on index page
  sources/platform/actors/publishing/index.mdx
Labels: t-docs

#1280 docs: restructure & enhance documentation for Actor publication
  sources/platform/actors/publishing/publish.mdx
Labels: t-docs

#1279 docs: restructure content and enhance model descriptions
  sources/platform/actors/publishing/monetize.mdx
Labels: t-docs

#1291 fix: scroll api sidebar on load
  apify-docs-theme/static/js/custom.js
Labels: adhoc, t-tooling

#1261 docs: add resourceType property to support storage picker
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-dataset-json.png
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-dataset.png
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-datasets.png
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, t-console

#1292 docs: fix typo
  sources/platform/actors/publishing/index.mdx
  sources/platform/integrations/ai/openai_assistants.md
Labels: documentation, adhoc, t-docs

#1286 fix: space between header and flags added
  apify-docs-theme/src/theme/custom.css
Labels: t-c&c

#1299 feat(docs): dateType property
  sources/platform/actors/development/actor_definition/input_schema/images/input-schema-date-relative.png
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-console

#1306 fix: fix Apify vale rule
  .github/styles/Apify/Apify.yml
Labels: documentation, adhoc, t-docs

#1244 feat: lessons about crawling and scraping product detail pages in Python
  sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
  sources/academy/webscraping/scraping_basics_python/13_platform.md
  sources/academy/webscraping/scraping_basics_python/images/pdp.png
  sources/academy/webscraping/scraping_basics_python/images/variants-js.gif
  sources/academy/webscraping/scraping_basics_python/images/variants.png
Labels: t-academy

#1314 fix: disable `@docusaurus/faster` for now
  apify-docs-theme/src/theme/custom.css
  docusaurus.config.js
  package-lock.json
  package.json
Labels: adhoc, t-tooling
