Repository apify/apify-docs, pull requests merged in 2025-08, with the labels that each got.

#1747 docs: add Actorization playbook
  sources/academy/platform/actorization_playbook.mdx
  sources/academy/platform/expert_scraping_with_apify/index.md
  sources/academy/platform/images/actorization-playbook/docling-apify-badge.png
  sources/academy/platform/running_a_web_server.md
Labels: documentation, t-docs

#1755 fix: support `cmd+k` to open the search modal
  apify-docs-theme/package.json
  apify-docs-theme/src/theme/SearchBar/index.js
  package-lock.json
Labels: adhoc, t-tooling

#1758 chore: bump TS dependency and disable problematic `indent` eslint rule
  eslint.config.mjs
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#1657 feat: update the downloading lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/04_downloading_html.md
Labels: t-academy

#1765 docs: add new tiles to integrations
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/ifttt.svg
  static/img/platform/integrations/n8n.svg
Labels: t-docs

#1766 chore: update apify logo in code block component
  apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
Labels: adhoc, t-console

#1650 feat: Improve documentation page titles
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/platform/actors/development/actor_definition/input_schema/index.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-management

#1757 feat: update CTA button border radius to 8px
  apify-docs-theme/src/theme/Navbar/CTA/styles.module.css
Labels: low priority, t-web

#1768 docs(mcp): add claude desktp dxt section
  sources/platform/integrations/ai/mcp.md
Labels: t-ai

#1746 fix: wrong output schema field types
  sources/platform/actors/development/actor_definition/dataset_schema/index.md
Labels: t-core-services

#1779 docs: remove outdated video from docs
  sources/platform/integrations/programming/github.md
Labels: documentation, t-docs

#1778 docs: update plan names
  sources/platform/limits.md
Labels: documentation, adhoc, t-docs

#1789 fix: remove `git-cliff` unreleased markers from changelogs
  apify-docs-theme/src/markdown.js
Labels: adhoc, t-tooling

#1780 docs: make inkeep and kapa display docs first when using search
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/SearchBar/index.js
Labels: documentation, adhoc, t-docs

#1767 docs: add new signed URL fields to dataset & key-value store
  apify-api/openapi/components/schemas/datasets/Dataset.yaml
  apify-api/openapi/components/schemas/key-value-stores/KeyValueStore.yaml
  apify-api/openapi/components/schemas/key-value-stores/ListOfKeysResponse.yaml
Labels: adhoc, t-core-services

#1782 feat: enable comma-separated status filtering across updated endpoints
  apify-api/openapi/paths/actor-runs/actor-runs.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs.yaml
Labels: t-integrations

#1790 docs: add note about negative profit isolation
  .vale.ini
  sources/platform/actors/publishing/monetize.mdx
Labels: documentation, adhoc, t-docs

#1695 docs: prepare docs for gumloop addition
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/platform/integrations/workflows-and-notifications/gmail.md
  sources/platform/integrations/workflows-and-notifications/gumloop/images/apify_credential_gumloop.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/apify_task_runner_node.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/apify_task_runner_node_library.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/create_apify_task.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/generate_apify_token.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/instagram/input-outputs.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/instagram/mcp-node-image.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/instagram/node.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/instagram/prompt.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/maps/input-outputs.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/maps/mcp-node-image.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/maps/node.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/maps/prompt.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/start_apify_task.png
  sources/platform/integrations/workflows-and-notifications/gumloop/images/tiktok/input-output.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/tiktok/mcp-node-image.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/tiktok/node.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/tiktok/prompt.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/youtube/input-outputs.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/youtube/mcp-node-image.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/youtube/node.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/images/youtube/prompt.jpeg
  sources/platform/integrations/workflows-and-notifications/gumloop/index.md
  sources/platform/integrations/workflows-and-notifications/gumloop/instagram.md
  sources/platform/integrations/workflows-and-notifications/gumloop/maps.md
  sources/platform/integrations/workflows-and-notifications/gumloop/tiktok.md
  sources/platform/integrations/workflows-and-notifications/gumloop/youtube.md
  sources/platform/integrations/workflows-and-notifications/ifttt.md
  sources/platform/integrations/workflows-and-notifications/slack.md
  sources/platform/integrations/workflows-and-notifications/telegram.md
Labels: documentation, t-docs

#1784 docs: add storage pricing calculator component
  sources/platform/storage/dataset.md
  sources/platform/storage/index.md
  sources/platform/storage/request_queue.md
  sources/platform/storage/usage.md
  src/components/StoragePricingCalculator/StoragePricingCalculator.module.css
  src/components/StoragePricingCalculator/index.jsx
Labels: t-docs

#1791 docs: add cursor rules
  .cursor/rules/api-documentation.mdc
  .cursor/rules/content-formatting.mdc
  .cursor/rules/documentation-style.mdc
  .cursor/rules/file-organization.mdc
  .cursor/rules/quality-standards.mdc
Labels: documentation, t-docs

#1807 docs: introduce CoC for community
  sources/legal/latest/policies/community-code-of-conduct
Labels: t-docs

#1812 refactor: revert kapa and inkeep search to algolia
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/SearchBar/index.js
Labels: adhoc, t-tooling

#1815 docs: hide make apps docs
  sources/platform/integrations/workflows-and-notifications/make/facebook.md
  sources/platform/integrations/workflows-and-notifications/make/instagram.md
Labels: documentation, adhoc, t-docs

#1814 docs: community coc update
  sources/legal/latest/policies/community-code-of-conduct.md
Labels: t-docs

#1801 fix: Always clear cache when on MCP page to help with redirect issue
  apify-docs-theme/static/js/custom.js
  sources/platform/integrations/ai/mcp.md
Labels: t-ai

#1824 fix: Move LLMButtons component to theme
  apify-docs-theme/src/theme/LLMButtons/CopyForLLM/index.tsx
  apify-docs-theme/src/theme/LLMButtons/ViewAsMarkdown/index.tsx
  apify-docs-theme/src/theme/LLMButtons/index.tsx
  apify-docs-theme/src/theme/LLMButtons/styles.module.css
  apify-docs-theme/src/theme/MDXComponents/index.js
  package-lock.json
  src/theme/DocItem/Content/index.js
  tsconfig.eslint.json
Labels: adhoc, t-web

#1817 docs: upgrades for privilege-less Docker images
  sources/platform/actors/development/actor_definition/docker.md
Labels: adhoc, t-tooling

#1762 feat: update the saving lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
Labels: t-academy

#1839 chore: skip fragment link checks with lychee
  .github/workflows/lychee.yml
Labels: adhoc, t-tooling

#1760 feat: update the parsing lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_javascript2/index.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
Labels: t-academy

#1853 refactor: adjust navbar item border-radius to 0.8rem
  apify-docs-theme/src/theme/custom.css
Labels: t-web

#1851 docs(mcp): update to reflect the new configuration spec
  sources/platform/integrations/ai/mcp.md
Labels: t-ai

#1861 feat: scrape prices as cents, avoid Decimal
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
  sources/academy/webscraping/scraping_basics_python/13_platform.md
Labels: t-academy
