Repository apify/apify-docs, pull requests merged in 2025-09, with the labels that each got.

#1865 fix: Add accept headers to silence 401 Unauthorized error
  apify-docs-theme/static/js/custom.js
Labels: t-ai

#1871 chore(ci): ignore links in `lychee` check
  .lycheeignore
Labels: adhoc, t-tooling

#1848 feat: update the platform lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
  sources/academy/webscraping/scraping_basics_python/13_platform.md
Labels: t-academy

#1846 feat: update the scraping variants lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
Labels: t-academy

#1847 feat: update the framework lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
Labels: t-academy

#1879 refactor: use for/of and .toArray() when looping over Cheerio selections
  sources/academy/webscraping/scraping_basics_javascript2/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_javascript2/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
  sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
  sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
  sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
Labels: t-academy

#1877 fix: a few small fixes in both Python and JS courses for beginners
  sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
Labels: t-academy

#1880 fix: missing semicolon
  sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
  sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
  sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
Labels: t-academy

#1881 style: use Markdown's automatic numbering
  sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
Labels: t-academy

#1873 feat: tidy up the tutorials navigation
  nginx.conf
  sources/academy/tutorials/api/index.md
  sources/academy/tutorials/api/retry_failed_requests.md
  sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
  sources/academy/tutorials/api/using_apify_from_php.md
  sources/academy/tutorials/apify_scrapers/index.md
  sources/academy/tutorials/node_js/index.md
  sources/academy/tutorials/php/index.md
  sources/academy/tutorials/python/index.md
Labels: t-academy

#1902 feat: update Microsoft styles
  .github/styles/Microsoft/Accessibility.yml
  .github/styles/Microsoft/Adverbs.yml
  .github/styles/Microsoft/ComplexWords.yml
  .github/styles/Microsoft/Dashes.yml
  .github/styles/Microsoft/FirstPerson.yml
  .github/styles/Microsoft/GenderBias.yml
  .github/styles/Microsoft/HeadingPunctuation.yml
  .github/styles/Microsoft/Hyphens.yml
  .github/styles/Microsoft/Negative.yml
  .github/styles/Microsoft/Plurals.yml
  .github/styles/Microsoft/RangeFormat.yml
  .github/styles/Microsoft/RangeTime.yml
  .github/styles/Microsoft/Ranges.yml
  .github/styles/Microsoft/Terms.yml
  .github/styles/Microsoft/URLFormat.yml
  .github/styles/Microsoft/Wordiness.yml
  .vale.ini
Labels: documentation, adhoc, t-docs

#1909 chore: remove Biel.AI AI assistant widget
  apify-docs-theme/src/theme/custom.css
  docusaurus.config.js
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#1911 fix: Correct meta descriptions
  docusaurus.config.js
  package-lock.json
Labels: t-web

#1933 docs: revert changes to URL
  nginx.conf
  sources/platform/integrations/ai/llama.md
  sources/platform/integrations/index.mdx
Labels: documentation, adhoc, t-docs

#1918 feat: Improve llms.txt file indentation
  package-lock.json
  package.json
  scripts/indentLlmsFile.mjs
Labels: t-web

#1935 fix: nginx configuration; add nginx linter
  .github/workflows/nginx.conf-test.yaml
  nginx.conf
Labels: adhoc, t-infra

#1938 docs: change back the slug to llama-index
  sources/platform/integrations/ai/llama.md
  sources/platform/integrations/index.mdx
Labels: documentation, adhoc, t-docs
