Repository apify/apify-docs, pull requests merged in 2025-10, with the labels that each got.

#1927 docs: overhaul mcp docs
  sources/platform/integrations/ai/mcp.md
Labels: documentation, t-docs

#1962 fix: move `DocSidebarItem/Category` to `@apify/docs-theme`
  apify-docs-theme/src/theme/DocSidebarItem/Category/index.js
Labels: t-tooling

#1964 docs: fix client links rendering in dark mode
  apify-api/openapi/paths/datasets/datasets@{datasetId}.yaml
  apify-api/plugins/decorators/client-references-links-decorator.js
  apify-docs-theme/src/theme/custom.css
Labels: t-tooling

#1961 docs: Update changing monetization setting
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  sources/platform/actors/publishing/monetize/index.mdx
Labels: t-c&c

#1956 feat: LLMs dropdown
  apify-docs-theme/src/theme/DocItemContent/index.js
  apify-docs-theme/src/theme/DocItemContent/styles.module.css
  apify-docs-theme/src/theme/LLMButtons/CopyForLLM/index.jsx
  apify-docs-theme/src/theme/LLMButtons/ViewAsMarkdown/index.jsx
  apify-docs-theme/src/theme/LLMButtons/index.jsx
  apify-docs-theme/src/theme/LLMButtons/styles.module.css
  docusaurus.config.js
  package-lock.json
  package.json
Labels: t-web

#1966 docs: Fix dataset validation python code example
  sources/platform/actors/development/actor_definition/dataset_schema/validation.md
Labels: bug, documentation, adhoc, t-tooling

#1978 chore: drop camel case properties from analytics [internal]
  src/plugins/docusaurus-plugin-segment/segment.js
Labels: t-web, analytics

#1991 docs: fix broken link
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, adhoc, t-docs

#1989 fix: Remove Claude integration
  apify-docs-theme/src/theme/LLMButtons/index.jsx
  package-lock.json
Labels: adhoc, t-web

#1937 feat: enable Kapa AI chat widget
  apify-docs-theme/package.json
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/SearchBar/index.js
  apify-docs-theme/src/theme/SearchBar/styles.css
  package-lock.json
  static/inkeep-overrides.css
Labels: adhoc, t-tooling
