Repository apify/apify-docs, pull requests merged in 2025-01, with the labels that each got.

#1370 feat: add x-legacy-doc-urls to run charge endpoints
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@charge.yaml
Labels: adhoc, t-c&c

#1360 feat(api): dataset fields statistics
  apify-api/openapi/components/schemas/datasets/DatasetFieldStatistics.yaml
  apify-api/openapi/components/schemas/datasets/GetDatasetStatisticsResponse.yaml
  apify-api/openapi/components/tags.yaml
  apify-api/openapi/components/x-tag-groups.yaml
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/datasets/datasets@{datasetId}@statistics.yaml
  package-lock.json
Labels: t-console

#1387 docs: fix mdlint block quote issue
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/project_setup.md
Labels: documentation, adhoc, t-docs

#1371 fix: various OpenAPI plugin fixes
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@run-sync.yaml
  apify-docs-theme/src/theme/NotFound.jsx
  apify-docs-theme/src/theme/SearchPage/index.js
  apify-docs-theme/src/theme/custom.css
  apify-docs-theme/static/js/custom.js
  docusaurus.config.js
  patches/docusaurus-plugin-openapi-docs+0.0.0-961.patch
  sources/api/sidebars.js
  src/theme/DocSidebarItem/Category/index.js
Labels: adhoc, t-tooling

#1391 fix: rename requirements.txt so its not picked up by dependabot and renovate
  apify-api/scripts/.requirements.txt
Labels: adhoc, t-tooling

#1395 fix: scope the sidebar changes to openapi plugin
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-tooling

#1394 feat: Promoting SOC 2 at security page and in the footer
  apify-docs-theme/package-lock.json
  apify-docs-theme/src/config.js
  package-lock.json
  sources/platform/images/security/soc2-logo.png
  sources/platform/security.md
Labels: adhoc, t-platform

#1373 feat(integrations): Update make.com documentation
  sources/platform/integrations/images/make-com/make-com-async-1.png
  sources/platform/integrations/images/make-com/make-com-async-2.png
  sources/platform/integrations/images/make-com/make-com-async-3.png
  sources/platform/integrations/images/make-com/make-com-sync-1.png
  sources/platform/integrations/images/make-com/make-com-sync-2.png
  sources/platform/integrations/images/make-com/make-com-sync-3.png
  sources/platform/integrations/images/make-com/make-com-sync-4.png
  sources/platform/integrations/workflows-and-notifications/make.md
Labels: t-platform

#1405 chore: bump dependencies
  .gitignore
  apify-docs-theme/package-lock.json
  apify-docs-theme/package.json
  package-lock.json
Labels: adhoc, t-tooling

#1406 fix: rename `requirements.txt` again, so dependabot ignores it when checking security issues
  apify-api/scripts/script-requirements.txt
Labels: adhoc, t-tooling

#1331 docs: fix Actor capitalization throughout open api docs
  apify-api/openapi/paths/actor-runs/actor-runs.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@abort.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@metamorph.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@reboot.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@resurrect.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@webhooks.yaml
  apify-api/openapi/paths/actors/acts.yaml
  apify-api/openapi/paths/actors/acts@{actorId}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs@{runId}@metamorph.yaml
  apify-api/openapi/paths/logs/logs@{buildOrRunId}.yaml
  apify-api/openapi/paths/schedules/schedules@{scheduleId}@log.yaml
  apify-api/openapi/paths/store/store.yaml
  apify-api/openapi/paths/webhooks/webhooks.yaml
Labels: t-docs

#1345 docs: add spell check capabilities to Vale linter
  .github/styles/config/vocabularies/Docs/accept.txt
  .github/workflows/typos-check.yaml
  .github/workflows/vale.yaml
  .vale.ini
  _typos.toml
  sources/academy/webscraping/anti_scraping/techniques/fingerprinting.md
  sources/academy/webscraping/api_scraping/general_api_scraping/cookies_headers_tokens.md
  sources/platform/actors/development/actor_definition/actor_json.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
  sources/platform/actors/development/builds_and_runs/builds.md
  sources/platform/actors/development/builds_and_runs/state_persistence.md
  sources/platform/actors/development/deployment/continuous_integration.md
  sources/platform/actors/development/deployment/index.md
  sources/platform/actors/development/deployment/source_types.md
  sources/platform/actors/development/performance.md
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/actors/development/programming_interface/system_events.md
  sources/platform/actors/development/quick_start/start_locally.md
  sources/platform/actors/publishing/badge.mdx
  sources/platform/actors/running/usage_and_resources.md
  sources/platform/integrations/actors/index.md
  sources/platform/integrations/actors/integrating_actors_via_api.md
  sources/platform/integrations/ai/milvus.md
  sources/platform/integrations/data-storage/drive.md
  sources/platform/integrations/programming/api.md
  sources/platform/integrations/programming/webhooks/actions.md
  sources/platform/integrations/workflows-and-notifications/gmail.md
  sources/platform/integrations/workflows-and-notifications/telegram.md
  sources/platform/monitoring/index.md
  sources/platform/proxy/datacenter_proxy.md
  sources/platform/proxy/index.md
  sources/platform/proxy/usage.md
  sources/platform/storage/key_value_store.md
  sources/platform/storage/request_queue.md
Labels: t-docs

#1408 fix: rename script requirements
  apify-api/scripts/requirements.bin
Labels: adhoc, t-tooling

#1410 chore: switch to algoliasearch v5
  apify-docs-theme/package.json
  apify-docs-theme/src/theme/SearchPage/index.js
  package-lock.json
  package.json
Labels: adhoc, t-tooling

#1409 docs: dpa update
  sources/legal/latest/terms/data-processing-addendum.md
Labels: t-docs

#1411 feat: switch new OpenAPI docs to `/api/v2`
  apify-api/scripts/script-requirements.txt
  apify-docs-theme/src/theme/custom.css
  apify-docs-theme/static/js/custom.js
  docusaurus.config.js
  src/theme/DocCard/index.js
  src/theme/DocSidebarItem/Category/index.js
  static/robots.txt
Labels: adhoc, tech roadmap, t-tooling

#1316 feat: first lesson about DevTools
  sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
  sources/academy/webscraping/scraping_basics_python/images/devtools-console-textcontent.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-console-variable.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-console.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-element-selection.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-elements-tab.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-exercise-cnn.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-exercise-fifa.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-hover.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-wikipedia.png
Labels: t-academy

#1412 fix: Another round of OpenAPI fixes
  apify-api/openapi/components/tags.yaml
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}.yaml
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@log.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}.yaml
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@abort.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@input.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs.yaml
  apify-api/openapi/paths/actors/acts.yaml
  apify-api/openapi/paths/actors/acts@{actorId}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs@{runId}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs@{runId}@abort.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs@{runId}@metamorph.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs@{runId}@resurrect.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@versions@{versionNumber}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@versions@{versionNumber}@env-vars.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@versions@{versionNumber}@env-vars@{envVarName}.yaml
  apify-api/openapi/paths/datasets/datasets.yaml
  apify-api/openapi/paths/datasets/datasets@{datasetId}.yaml
  apify-api/openapi/paths/datasets/datasets@{datasetId}@items.yaml
  apify-api/openapi/paths/logs/logs@{buildOrRunId}.yaml
  apify-api/openapi/paths/request-queues/request-queues.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@head.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@batch.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}.yaml
  apify-api/openapi/paths/store/store.yaml
  apify-api/openapi/paths/webhook-dispatches/webhook-dispatches.yaml
  apify-api/openapi/paths/webhooks/webhooks.yaml
  apify-api/openapi/paths/webhooks/webhooks@{webhookId}.yaml
  apify-docs-theme/src/theme/MDXComponents/A.js
  apify-docs-theme/src/theme/custom.css
  apify-docs-theme/static/js/custom.js
  docusaurus.config.js
  src/theme/DocCard/index.js
Labels: adhoc, t-tooling

#1413 fix: remove trailing slash from internal URL
  apify-docs-theme/src/config.js
Labels: adhoc, t-tooling

#1414 feat: allow downloading openapi specs (without decorators)
  .gitignore
  apify-docs-theme/src/theme/custom.css
  docusaurus.config.js
  package.json
Labels: adhoc, t-tooling

#1303 feat: lesson about using a framework
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
  sources/academy/webscraping/scraping_basics_python/images/dataset-item.png
Labels: t-academy

#1421 fix: treat component props as immutable to make react happy again
  apify-docs-theme/src/theme/MDXComponents/A.js
Labels: adhoc, t-tooling

#1423 feat: added default build endpoint
  apify-api/openapi/components/tags.yaml
  apify-api/openapi/components/x-tag-groups.yaml
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
Labels: adhoc, t-platform

#1426 fix: correct URLs for openapi download links
  docusaurus.config.js
Labels: adhoc, t-tooling

#1427 fix: use correct `unist-util-visit-parents` imports
  apify-docs-theme/src/markdown.js
Labels: adhoc, t-tooling

#1415 docs: add full schema link
  apify-api/openapi/openapi.yaml
Labels: documentation, adhoc, t-docs

#1428 fix: do not double wrap GitHub user links in changelog
  apify-docs-theme/src/markdown.js
Labels: adhoc, t-tooling

#1429 docs: Lenka/dpa
  sources/legal/latest/policies/privacy-policy.md
  sources/legal/latest/terms/data-processing-addendum.md
Labels: t-docs

#1433 docs: vale fixes
  .github/styles/config/vocabularies/Docs/accept.txt
  .vale.ini
  sources/academy/platform/expert_scraping_with_apify/apify_api_and_client.md
  sources/academy/tutorials/node_js/handle_blocked_requests_puppeteer.md
  sources/academy/tutorials/node_js/js_in_html.md
  sources/academy/tutorials/node_js/processing_multiple_pages_web_scraper.md
  sources/academy/webscraping/api_scraping/index.md
Labels: documentation, adhoc, t-docs

#1267 fix: start_locally.md typo
  sources/platform/actors/development/quick_start/start_locally.md
Labels: adhoc

#1436 chore: update lockfile
  package-lock.json
  patches/docusaurus-plugin-openapi-docs+4.3.2.patch
  patches/docusaurus-theme-openapi-docs+4.3.2.patch
Labels: adhoc, t-tooling

#1438 feat: Add llms.txt
  static/llms.txt
Labels: adhoc, t-web

#1434 refactor: rename OpenAPI endpoints
  apify-api/openapi/components/tags.yaml
  apify-api/openapi/components/x-tag-groups.yaml
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@openapi.json.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}@openapi.json.yaml
Labels: adhoc, t-platform

#1435 feat: add standby readiness probe docs
  sources/platform/actors/development/programming_interface/actor_standby.md
Labels: t-platform
