Repository apify/apify-docs, pull requests merged in 2025-06, with the labels that each got.

#1609 docs: update Zapier integration with info about using OAuth
  sources/platform/integrations/images/zapier-allow-access.png
  sources/platform/integrations/images/zapier-choose-account.png
  sources/platform/integrations/workflows-and-notifications/zapier.md
Labels: t-docs

#1611 docs: update payment terms in Affiliate Program
  sources/legal/latest/terms/affiliate-program-terms-and-conditions.md
Labels: t-docs

#1599 docs: add Lindy integration guide
  sources/platform/integrations/ai/agno.md
  sources/platform/integrations/ai/aws_bedrock.md
  sources/platform/integrations/ai/flowise.md
  sources/platform/integrations/ai/images/lindy/lindy-action.png
  sources/platform/integrations/ai/images/lindy/lindy-instagram-actor.png
  sources/platform/integrations/ai/images/lindy/lindy-new-button.png
  sources/platform/integrations/ai/images/lindy/lindy-received.png
  sources/platform/integrations/ai/images/lindy/lindy-run-actor.png
  sources/platform/integrations/ai/images/lindy/lindy-scratch.png
  sources/platform/integrations/ai/images/lindy/lindy-trigger.png
  sources/platform/integrations/ai/lindy.md
  sources/platform/integrations/ai/llama.md
  sources/platform/integrations/ai/mastra.md
  sources/platform/integrations/ai/milvus.md
  sources/platform/integrations/ai/openai_assistants.md
  sources/platform/integrations/ai/pinecone.md
  sources/platform/integrations/ai/qdrant.md
Labels: documentation, t-docs

#1618 docs: rework emphasis to separate note
  sources/platform/integrations/ai/mcp.md
Labels: documentation, adhoc, t-docs

#1619 docs: fix typo
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
Labels: t-docs

#1612 feat: PPE + Standby
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/publishing/monetize.mdx
  sources/platform/actors/running/store.md
Labels: t-c&c

#1628 docs: Improve prefill documentation
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-tooling

#1632 docs: add console backend to the scope of the vdp
  sources/platform/security.md
Labels: documentation, adhoc, t-console, security related

#1630 docs: add additionalProperties to input schema specification
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: adhoc, t-console

#1638 docs: updates to formatting
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, adhoc, t-docs

#1642 feat: Add configurable search engine indexing behavior [internal]
  apify-docs-theme/src/config.js
  docusaurus.config.js
Labels: adhoc, t-platform

#1639 docs: rename Academy articles
  sources/academy/platform/deploying_your_code/deploying.md
  sources/academy/platform/deploying_your_code/docker_file.md
  sources/academy/platform/deploying_your_code/index.md
  sources/academy/platform/deploying_your_code/input_schema.md
  sources/academy/platform/deploying_your_code/inputs_outputs.md
  sources/academy/platform/deploying_your_code/output_schema.md
Labels: documentation, adhoc, t-docs

#1644 feat: rental Actors and AI agents
  sources/platform/actors/publishing/monetize.mdx
Labels: adhoc, t-c&c

#1643 fix: MCP server can add and remove Actors as default behavior
  sources/platform/integrations/ai/mcp.md
Labels: t-ai

#1649 docs: Add KVS recordExists operation to the OpenAPI spec
  apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@records@{recordKey}.yaml
Labels: adhoc, t-tooling

#1658 fix: re-order JSON and CSV in Python lessons
  sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
  sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
  sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
Labels: t-academy
