Repository apify/apify-docs, pull requests merged in 2025-02, with the labels that each got.

#1443 feat: update llms.txt
  static/llms.txt
Labels: t-ai

#1439 chore: update eslint to v9
  .eslintignore
  apify-api/openapi/code_samples/javascript/requestQueue_requests_post.js
  apify-docs-theme/src/markdown.js
  apify-docs-theme/src/roa-loader/index.js
  apify-docs-theme/src/theme.js
  apify-docs-theme/src/theme/ColorModeToggle/index.jsx
  apify-docs-theme/src/theme/DocSidebarItem/Link/index.jsx
  apify-docs-theme/src/theme/Footer/index.jsx
  apify-docs-theme/src/theme/Layout/index.jsx
  apify-docs-theme/src/theme/Navbar/MobileSidebar/PrimaryMenu/index.jsx
  apify-docs-theme/src/theme/NavbarItem/ComponentTypes.jsx
  apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
  apify-docs-theme/src/theme/SearchBar/index.js
  eslint.config.mjs
  examples/ts-parallel-scraping/orchestrator/src/main.ts
  package-lock.json
  package.json
  sitePlugin.js
  sources/academy/tutorials/node_js/caching_responses_in_puppeteer.js
  sources/academy/webscraping/scraping_basics_javascript/crawling/finding_links.js
  sources/api/sidebars.js
  src/components/ActionCard/ActionCard.tsx
  src/components/ActorTemplates/ActorTemplates.tsx
  src/components/ApiLink.jsx
  src/components/Button.tsx
  src/components/Card.jsx
  src/components/CardGrid.jsx
  src/components/CardWithIcon/CardWithIcon.tsx
  src/components/CardWithImageAndContent/ImageWithContent.tsx
  src/components/ChangeLog/ChangeLog.tsx
  src/components/GitButton.tsx
  src/components/Heading.tsx
  src/components/Hero/Hero.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/PlainCard/PlainCard.tsx
  src/components/PlatformCard.jsx
  src/components/SdkSection/SdkSection.tsx
  src/components/Section/Section.tsx
  src/components/Tabs.tsx
  src/components/Text.tsx
  src/components/UiLibraryWrapper.tsx
  src/pages/api/index.tsx
  src/pages/api/v2-old.js
  src/pages/open-source/index.tsx
  src/pages/sdk/index.tsx
  src/pages/versions.js
  tsconfig.eslint.json
Labels: t-tooling

#1441 feat: update langchain apify
  sources/platform/integrations/ai/haystack.md
  sources/platform/integrations/ai/langchain.md
  sources/platform/integrations/ai/langgraph.md
Labels: t-ai

#1365 feat: Add "Speeding up migrations" section to "State persistence"
  sources/platform/actors/development/builds_and_runs/state_persistence.md
Labels: adhoc, t-platform

#1446 docs: Update actions.md
  sources/platform/integrations/programming/webhooks/actions.md
Labels: adhoc, t-console

#1452 fix: remove possible infinite loop in the changelog transformation
  apify-docs-theme/src/markdown.js
Labels: adhoc, t-tooling

#1453 feat: add responsible disclosure guidelines to security page
  sources/platform/security.md
Labels: adhoc, t-console

#1456 docs: change codeowners file
  .github/CODEOWNERS
Labels: adhoc, t-docs

#1459 docs: fix nginx configuration
  nginx.conf
Labels: documentation, adhoc, t-docs

#1458 feat: Mention that webhooks are sent through select static IPs
  sources/platform/integrations/programming/webhooks/actions.md
Labels: adhoc, t-platform

#1465 docs: add missing word to copy on API landing page
  src/pages/api/index.tsx
Labels: documentation, adhoc, t-docs

#1447 docs: Update Gmail and Drive integration docs
  sources/platform/integrations/data-storage/drive.md
  sources/platform/integrations/images/google/google-integrations-accounts.png
  sources/platform/integrations/images/google/google-integrations-add.png
  sources/platform/integrations/images/google/google-integrations-connect-drive.png
  sources/platform/integrations/images/google/google-integrations-connect-gmail.png
  sources/platform/integrations/images/google/google-integrations-details-drive.png
  sources/platform/integrations/images/google/google-integrations-details-gmail.png
  sources/platform/integrations/workflows-and-notifications/gmail.md
Labels: adhoc, t-console

#1217 feat(academy): add advanced crawling section with sitemaps and search
  nginx.conf
  sources/academy/tutorials/node_js/scraping_from_sitemaps.md
  sources/academy/webscraping/advanced_web_scraping/crawling/crawling-sitemaps.md
  sources/academy/webscraping/advanced_web_scraping/crawling/crawling-with-search.md
  sources/academy/webscraping/advanced_web_scraping/crawling/images/pagination-filters.png
  sources/academy/webscraping/advanced_web_scraping/crawling/images/pagination.png
  sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
  sources/academy/webscraping/advanced_web_scraping/index.md
  sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
  sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
Labels: t-academy

#1467 docs: fix broken link in Schedules introduction
  apify-api/openapi/components/tags.yaml
Labels: documentation, adhoc, t-docs

#1468 chore: add consoleUrl field to storages
  apify-api/openapi/components/schemas/datasets/Dataset.yaml
  apify-api/openapi/components/schemas/key-value-stores/KeyValueStore.yaml
  apify-api/openapi/components/schemas/request-queues/RequestQueue.yaml
Labels: t-platform

#1425 feat: langflow ai integration docs
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/platform/integrations/ai/langflow.md
  sources/platform/integrations/images/langflow/agent_configuration.png
  sources/platform/integrations/images/langflow/agent_output.png
  sources/platform/integrations/images/langflow/apify_actors_configuration.png
  sources/platform/integrations/images/langflow/apify_actors_output.png
  sources/platform/integrations/images/langflow/apify_actors_output_data.png
  sources/platform/integrations/images/langflow/apify_actors_output_data_filtered.png
  sources/platform/integrations/images/langflow/apify_actors_output_filter.png
  sources/platform/integrations/images/langflow/apify_actors_run.png
  sources/platform/integrations/images/langflow/bundles_apify.png
  sources/platform/integrations/images/langflow/chat_message_output.png
  sources/platform/integrations/images/langflow/flow.png
  sources/platform/integrations/images/langflow/new_blank_flow.png
  sources/platform/integrations/images/langflow/playground.png
Labels: t-ai

#1461 docs: initial marketing playbook content move
  .github/styles/config/vocabularies/Docs/accept.txt
  nginx.conf
  sources/academy/platform/get_most_of_actors/actor_basics/_category_.yaml
  sources/academy/platform/get_most_of_actors/actor_basics/actor_description_seo_description.md
  sources/academy/platform/get_most_of_actors/actor_basics/actors-and-emojis.md
  sources/academy/platform/get_most_of_actors/actor_basics/how-to-create-actor-readme.md
  sources/academy/platform/get_most_of_actors/actor_basics/images/actor-description-name.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/actor-description-store.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/actor-name.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/actor-seo-name.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/change_Actor_description.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/changing_Actor_name_and_SEO_name.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/changing__SEO_name.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/how-and-where-to-set-the-actor-url-console.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/how-and-where-to-set-the-actor-url.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/readme.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/seo_description.png
  sources/academy/platform/get_most_of_actors/actor_basics/images/what-is-actor-url.png
  sources/academy/platform/get_most_of_actors/actor_basics/importance-of-actor-url.md
  sources/academy/platform/get_most_of_actors/actor_basics/name-your-actor.md
  sources/academy/platform/get_most_of_actors/index.md
  sources/academy/platform/get_most_of_actors/interact_with_users/_category_.yaml
  sources/academy/platform/get_most_of_actors/interact_with_users/emails_to_actor_users.md
  sources/academy/platform/get_most_of_actors/interact_with_users/images/issues-tab-example.png
  sources/academy/platform/get_most_of_actors/interact_with_users/issues_tab.md
  sources/academy/platform/get_most_of_actors/interact_with_users/your_store_bio.md
  sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
  sources/academy/platform/get_most_of_actors/product_optimization/_category_.yaml
  sources/academy/platform/get_most_of_actors/product_optimization/actor_bundles.md
  sources/academy/platform/get_most_of_actors/product_optimization/how_to_create_a_great_input_schema.md
  sources/academy/platform/get_most_of_actors/product_optimization/images/description-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/improved-input-schema-example.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/section-description-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/sections-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/title-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/toggle-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/tooltips-sshot.png
  sources/academy/platform/get_most_of_actors/product_optimization/images/worse-input-schema.png
  sources/academy/platform/get_most_of_actors/promote_your_actor/_category_.yaml
  sources/academy/platform/get_most_of_actors/promote_your_actor/blogs_and_blog_resources.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/parasite_seo.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/product_hunt.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/seo.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/social_media.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/video_tutorials.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/webinars.md
  sources/academy/platform/get_most_of_actors/store_basics/_category_.yaml
  sources/academy/platform/get_most_of_actors/store_basics/actor_success_stories.md
  sources/academy/platform/get_most_of_actors/store_basics/how_actor_monetization_works.md
  sources/academy/platform/get_most_of_actors/store_basics/how_store_works.md
  sources/academy/platform/get_most_of_actors/store_basics/how_to_build_actors.md
  sources/academy/platform/get_most_of_actors/store_basics/ideas_page_and_its_use.md
  sources/academy/platform/get_most_of_actors/store_basics/images/analytisc-example.png
  sources/academy/platform/get_most_of_actors/store_basics/images/ppr-model.png
  sources/academy/platform/get_most_of_actors/store_basics/images/rental-model.png
  sources/platform/actors/running/store.md
Labels: documentation, t-academy, t-docs

#1462 docs: new OSS fair share terms
  sources/legal/latest/terms/fair-share-program-terms-and-conditions.md
Labels: t-docs

#1471 fix: fix redirect of marketing playbook
  nginx.conf
Labels: adhoc, t-tooling

#1472 docs: fix broken links in Actor marketing playbook
  sources/academy/platform/get_most_of_actors/actor_basics/how-to-create-actor-readme.md
  sources/academy/platform/get_most_of_actors/actor_basics/name-your-actor.md
  sources/academy/platform/get_most_of_actors/promote_your_actor/parasite_seo.md
  sources/academy/platform/get_most_of_actors/store_basics/how_store_works.md
  sources/academy/platform/get_most_of_actors/store_basics/how_to_build_actors.md
Labels: documentation, adhoc, t-docs

#1473 docs: Fix ActorRunStats OpenAPI schema
  apify-api/openapi/components/schemas/actor-runs/RunStats.yaml
Labels: adhoc, t-tooling

#1476 docs: merge monetization content in platform docs
  sources/platform/actors/publishing/images/actor-analytisc.png
  sources/platform/actors/publishing/images/actor-insights.png
  sources/platform/actors/publishing/images/actor_analytics.png
  sources/platform/actors/publishing/images/actor_insights.png
  sources/platform/actors/publishing/images/monetization-section.png
  sources/platform/actors/publishing/images/monetization_section.png
  sources/platform/actors/publishing/images/monetization_wizard.png
  sources/platform/actors/publishing/images/monetize_actor_set_up_monetization.png
  sources/platform/actors/publishing/monetize.mdx
Labels: documentation, t-docs

#1481 docs: add new section regarding PPE based on alpha PPE docs
  sources/platform/actors/publishing/images/monetization_wizard.png
  sources/platform/actors/publishing/images/ppe-wizard.png
  sources/platform/actors/publishing/images/ppr-wizard.png
  sources/platform/actors/publishing/images/rental-wizard.png
  sources/platform/actors/publishing/monetize.mdx
Labels: documentation, t-docs

#1477 feat: analytics support
  .github/workflows/deploy.yaml
  .github/workflows/docs.yaml
  .github/workflows/lychee.yml
  .github/workflows/test.yaml
  docusaurus.config.js
Labels: adhoc, t-web

#1479 fix: details summary arrow
  src/theme/Details/index.js
  src/theme/Details/styles.module.css
Labels: bug, t-web
