Repository apify/apify-docs, pull requests merged in 2025-03, with the labels that each got.

#1485 feat: add maxTotalChargeUsd param
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@run-sync.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@run-sync-get-dataset-items.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@run-sync.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@runs.yaml
  sources/platform/actors/development/programming_interface/environment_variables.md
  sources/platform/api_v2/api_v2_reference.apib
Labels: adhoc, t-c&c

#1488 docs: add PPE pricing model to Actor marketing playbook
  sources/academy/platform/get_most_of_actors/store_basics/how_actor_monetization_works.md
  sources/academy/platform/get_most_of_actors/store_basics/images/ppe-model.png
Labels: documentation, t-docs

#1492 docs: Add PPE-related properties to OpenAPI spec
  apify-api/openapi/components/schemas/actor-pricing-info/ActorChargeEvent.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/ActorRunPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/CommonActorPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/FlatPricePerMonthActorPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/FreeActorPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/PayPerEventActorPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-pricing-info/PricePerDatasetItemActorPricingInfo.yaml
  apify-api/openapi/components/schemas/actor-runs/Run.yaml
  apify-api/openapi/components/schemas/actors/Actor.yaml
  apify-api/openapi/components/schemas/actors/CreateActorRequest.yaml
  apify-api/openapi/components/schemas/actors/UpdateActorRequest.yaml
Labels: t-tooling

#1495 chore: Set up CODEOWNERS for openapi specs
  .github/CODEOWNERS
Labels: adhoc, t-tooling

#1489 feat(platform/integrations): add Airtable integration guide
  sources/platform/integrations/data-storage/airtable.md
  sources/platform/integrations/images/airtable/connect-account-1.png
  sources/platform/integrations/images/airtable/connect-account-2.png
  sources/platform/integrations/images/airtable/set-up-integration-1.png
  sources/platform/integrations/images/airtable/set-up-integration-2.png
  sources/platform/integrations/images/airtable/set-up-integration-3.png
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/airtable.svg
Labels: adhoc, t-console

#1321 feat: third lesson about DevTools
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/03_devtools_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/images/devtools-exercise-fandom.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-exercise-guardian1.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-exercise-guardian2.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-extracting-price.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-extracting-text.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-extracting-title.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-product-details.png
Labels: t-academy

#1484 feat: add crewai integration docs
  sources/platform/integrations/ai/crewai.md
Labels: t-ai

#1494 feat: add new item to open source dropdown
  apify-docs-theme/src/config.js
Labels: t-docs

#1501 docs: adding PPE to store terms
  sources/legal/latest/terms/store-publishing-terms-and-conditions.md
Labels: t-docs

#1503 fix: import `unified` plugins correctly in Node `>=22.12`
  apify-docs-theme/src/markdown.js
Labels: adhoc, t-tooling

#1502 feat: add redirects for `crawlee.dev/js`
  nginx.conf
Labels: adhoc, t-tooling

#1512 docs: fix broken links
  repomix-output.xml
  sources/academy/platform/get_most_of_actors/store_basics/how_actor_monetization_works.md
  sources/platform/integrations/ai/langflow.md
Labels: t-docs

#1505 feat: mastra mcp agent
  sources/platform/integrations/ai/mastra.md
  sources/platform/integrations/index.mdx
  static/img/platform/integrations/crewai.png
  static/img/platform/integrations/langgraph.png
  static/img/platform/integrations/mastra.png
Labels: t-ai

#1514 docs: add redirect and add new item to robots.txt
  nginx.conf
  static/robots.txt
Labels: adhoc, t-docs

#1516 chore: update lockfile
  .eslintrc.json
  apify-api/plugins/decorators/code-samples-decorator.js
  apify-docs-theme/src/theme.js
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  apify-docs-theme/src/theme/SearchBar/index.js
  apify-docs-theme/src/theme/TOCItems/index.jsx
  package-lock.json
  package.json
  sources/academy/tutorials/node_js/caching_responses_in_puppeteer.js
  sources/academy/tutorials/node_js/dealing_with_dynamic_pages.js
  sources/academy/tutorials/node_js/scraping_from_sitemaps.js
  src/pages/index.tsx
  src/pages/open-source/index.tsx
  src/theme/DocCard/index.js
  src/theme/DocSidebarItem/Category/index.js
  tools/utils/collectSlugs.js
  tools/utils/externalLink.js
Labels: adhoc, t-tooling

#1515 feat: analytics proxy support
  docusaurus.config.js
Labels: adhoc, t-web
