Repository apify/apify-docs, pull requests merged in 2025-05, with the labels that each got.

#1560 fix: exercises using the F1 website got outdated
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
Labels: t-academy

#1518 chore: configuration for docs-preview
  nginx.conf
Labels: adhoc, t-platform, infrastructure

#1562 feat: add type hints
  sources/academy/webscraping/scraping_basics_python/12_framework.md
Labels: t-academy

#1552 fix: remove the TypeScript course
  nginx.conf
  sources/academy/webscraping/typescript/enums.md
  sources/academy/webscraping/typescript/images/another-error.png
  sources/academy/webscraping/typescript/images/constant-autofill.png
  sources/academy/webscraping/typescript/images/epic-autocomplete.png
  sources/academy/webscraping/typescript/images/is-any.png
  sources/academy/webscraping/typescript/images/no-more-error.png
  sources/academy/webscraping/typescript/images/number-inference.png
  sources/academy/webscraping/typescript/images/object-inference.png
  sources/academy/webscraping/typescript/images/object-type-error.png
  sources/academy/webscraping/typescript/images/parameter-type.png
  sources/academy/webscraping/typescript/images/pasted-example.png
  sources/academy/webscraping/typescript/images/promise-any.png
  sources/academy/webscraping/typescript/images/replace-with-unknown.png
  sources/academy/webscraping/typescript/images/return-inferred.png
  sources/academy/webscraping/typescript/images/string-not-number.png
  sources/academy/webscraping/typescript/images/typescript-error.png
  sources/academy/webscraping/typescript/images/typescript-logo.webp
  sources/academy/webscraping/typescript/images/we-need-overloads.png
  sources/academy/webscraping/typescript/index.md
  sources/academy/webscraping/typescript/installation.md
  sources/academy/webscraping/typescript/interfaces.md
  sources/academy/webscraping/typescript/mini_project.md
  sources/academy/webscraping/typescript/type_aliases.md
  sources/academy/webscraping/typescript/unknown_and_type_assertions.md
  sources/academy/webscraping/typescript/using_types.md
  sources/academy/webscraping/typescript/using_types_continued.md
  sources/academy/webscraping/typescript/watch_mode_and_tsconfig.md
Labels: t-academy

#1529 feat(integrations): add Agno integration docs
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/platform/integrations/ai/agno.md
Labels: t-ai

#1575 fix: academy links should be absolute
  sources/academy/homepage_content.json
Labels: adhoc, t-tooling

#1540 docs: add Make apps documentation
  sources/platform/integrations/workflows-and-notifications/make/ai-crawling.md
  sources/platform/integrations/workflows-and-notifications/make/amazon.md
  sources/platform/integrations/workflows-and-notifications/make/facebook.md
  sources/platform/integrations/workflows-and-notifications/make/images/Apify_Console_token_for_Make.png
  sources/platform/integrations/workflows-and-notifications/make/images/Apify_token_on_Make.png
  sources/platform/integrations/workflows-and-notifications/make/images/ai-crawling/image 1.png
  sources/platform/integrations/workflows-and-notifications/make/images/ai-crawling/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/ai-crawling/wcc-signup.png
  sources/platform/integrations/workflows-and-notifications/make/images/amazon/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/amazon/image1.png
  sources/platform/integrations/workflows-and-notifications/make/images/facebook/actor-rental.png
  sources/platform/integrations/workflows-and-notifications/make/images/facebook/make-api-token.png
  sources/platform/integrations/workflows-and-notifications/make/images/facebook/signup.png
  sources/platform/integrations/workflows-and-notifications/make/images/facebook/start-rental.png
  sources/platform/integrations/workflows-and-notifications/make/images/instagram/Apify_Make_Sign_up_page.png
  sources/platform/integrations/workflows-and-notifications/make/images/instagram/Apify_Token_for_modules_on_Make.png
  sources/platform/integrations/workflows-and-notifications/make/images/maps/Screenshot_2025-04-22_at_12.45.33.png
  sources/platform/integrations/workflows-and-notifications/make/images/maps/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/maps/maps-signup.png
  sources/platform/integrations/workflows-and-notifications/make/images/search/image 1.png
  sources/platform/integrations/workflows-and-notifications/make/images/search/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/search/search-signup.png
  sources/platform/integrations/workflows-and-notifications/make/images/tiktok/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/tiktok/image1.png
  sources/platform/integrations/workflows-and-notifications/make/images/youtube/image.png
  sources/platform/integrations/workflows-and-notifications/make/images/youtube/image1.png
  sources/platform/integrations/workflows-and-notifications/make/index.md
  sources/platform/integrations/workflows-and-notifications/make/instagram.md
  sources/platform/integrations/workflows-and-notifications/make/maps.md
  sources/platform/integrations/workflows-and-notifications/make/search.md
  sources/platform/integrations/workflows-and-notifications/make/tiktok.md
  sources/platform/integrations/workflows-and-notifications/make/youtube.md
Labels: documentation, t-docs

#1576 docs: list FB make app docs
  sources/platform/integrations/workflows-and-notifications/make/facebook.md
Labels: documentation, adhoc, t-docs

#1577 docs: fix typos
  sources/platform/integrations/workflows-and-notifications/make/ai-crawling.md
  sources/platform/integrations/workflows-and-notifications/make/instagram.md
Labels: documentation, adhoc, t-docs

#1568 style: consistency fixes
  sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
  sources/academy/webscraping/scraping_basics_python/13_platform.md
  sources/academy/webscraping/scraping_basics_python/index.md
Labels: t-academy

#1580 docs: document `raw` query param in `logs`
  apify-api/openapi/paths/logs/logs@{buildOrRunId}.yaml
Labels: adhoc, t-tooling

#1581 docs: Mention that requests marked as handled are unlocked automatically
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}.yaml
Labels: adhoc, t-tooling

#1582 docs: fix links in fb make app
  sources/academy/platform/get_most_of_actors/store_basics/how_store_works.md
  sources/platform/integrations/workflows-and-notifications/make/facebook.md
Labels: documentation, adhoc, t-docs

#1588 docs: fix broken links
  sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
Labels: documentation, adhoc, t-docs

#1563 chore: docs PR previews
  .github/workflows/pr-previews.yaml
  apify-docs-theme/src/config.js
  docusaurus.config.js
  examples/ts-parallel-scraping/orchestrator/src/main.ts
Labels: adhoc, t-tooling

#1589 docs: fix links
  sources/academy/platform/get_most_of_actors/store_basics/how_to_build_actors.md
Labels: documentation, adhoc, t-docs

#1587 docs: Add cookie consent
  docusaurus.config.js
  src/plugins/docusaurus-plugin-segment/index.js
  src/plugins/docusaurus-plugin-segment/segment.js
Labels: t-web

#1593 fix: fix client side rendering of openapi docs
  docusaurus.config.js
  package-lock.json
  patches/docusaurus-plugin-openapi-docs+4.4.0.patch
  patches/docusaurus-theme-openapi-docs+4.4.0.patch
  src/plugins/docusaurus-plugin-segment/index.js
Labels: adhoc, t-tooling

#1595 fix: Preview Docs Environment Nginx rules
  nginx.conf
Labels: adhoc, t-infra

#1548 chore: add links to JS & python clients
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@openapi.json.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
Labels: adhoc, t-platform

#1596 chore: Remove Adam from OpenAPI codeowners
  .github/CODEOWNERS
Labels: adhoc, t-tooling

#1597 feat: Add maxItems and maxTotalChargeUsd to resurrect API doc
  apify-api/openapi/paths/actor-runs/actor-runs@{runId}@resurrect.yaml
Labels: t-c&c

#1585 docs: add webServerSchema field in actor definition
  sources/platform/actors/development/actor_definition/actor_json.md
Labels: documentation, adhoc, t-console
