Repository apify/apify-docs, pull requests merged in 2025-07, with the labels that each got.

#1652 feat: polish docs for payouts
  sources/platform/actors/publishing/monetize.mdx
Labels: t-c&c

#1672 revert: "feat: header facelift (#1662)"
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/Footer/index.jsx
  apify-docs-theme/src/theme/Footer/index.module.css
  apify-docs-theme/src/theme/Layout/index.jsx
  apify-docs-theme/src/theme/Navbar/CTA/index.jsx
  apify-docs-theme/src/theme/Navbar/CTA/styles.module.css
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  apify-docs-theme/src/theme/Navbar/Content/styles.module.css
  apify-docs-theme/src/theme/Navbar/MobileSidebar/Header/index.jsx
  apify-docs-theme/src/theme/SearchBar/index.js
  apify-docs-theme/src/theme/SearchBar/styles.css
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-web

#1676 feat: header facelift v2
  apify-docs-theme/package.json
  apify-docs-theme/src/config.js
  apify-docs-theme/src/theme/Footer/index.jsx
  apify-docs-theme/src/theme/Footer/index.module.css
  apify-docs-theme/src/theme/Layout/index.jsx
  apify-docs-theme/src/theme/Navbar/CTA/index.jsx
  apify-docs-theme/src/theme/Navbar/CTA/styles.module.css
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  apify-docs-theme/src/theme/Navbar/Content/styles.module.css
  apify-docs-theme/src/theme/Navbar/MobileSidebar/Header/index.jsx
  apify-docs-theme/src/theme/SearchBar/index.js
  apify-docs-theme/src/theme/SearchBar/styles.css
  apify-docs-theme/src/theme/SearchPage/index.js
  apify-docs-theme/src/theme/custom.css
  package-lock.json
  package.json
Labels: t-web

#1678 fix: navbar subtitle width
  apify-docs-theme/src/theme/custom.css
Labels: bug, adhoc, t-web

#1684 fix: analytics tracking [internal]
  apify-docs-theme/src/theme/Navbar/CTA/index.jsx
  src/plugins/docusaurus-plugin-segment/index.js
Labels: bug, adhoc, t-web

#1679 docs: fix typo in actor_json.md
  sources/platform/actors/development/actor_definition/actor_json.md
Labels: documentation, adhoc, low priority, t-docs

#1682 docs: Secret object/array inputs
  sources/platform/actors/development/actor_definition/input_schema/secret_input.md
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: t-console

#1706 docs: add `APIFY_USER_IS_PAYING` env var documentation
  sources/platform/actors/development/programming_interface/environment_variables.md
Labels: adhoc, t-core-services

#1710 chore: add markdown pages [internal]
  docusaurus.config.js
  package-lock.json
  package.json
  static/llms.txt
Labels: t-web

#1716 fix: allow builds without the segment API key
  src/plugins/docusaurus-plugin-segment/index.js
Labels: adhoc, t-tooling

#1699 docs: add n8n documentation
  sources/platform/integrations/images/n8n-api-auth.png
  sources/platform/integrations/images/n8n-get-dataset-items-example.png
  sources/platform/integrations/images/n8n-install-node-cloud.png
  sources/platform/integrations/images/n8n-install-node-self-hosted.png
  sources/platform/integrations/images/n8n-list-of-operations.png
  sources/platform/integrations/images/n8n-oauth.png
  sources/platform/integrations/images/n8n-run-actor-example.png
  sources/platform/integrations/images/n8n-trigger-example.png
  sources/platform/integrations/images/n8n-workflow-example.png
  sources/platform/integrations/workflows-and-notifications/n8n.md
Labels: documentation, t-docs

#1714 docs: redirect SDK JS `versions` page to changelog
  nginx.conf
Labels: adhoc, t-tooling

#1717 docs: Apify logo rebranding
  apify-docs-theme/static/img/apify_logo.svg
  apify-docs-theme/static/img/apify_sdk.svg
  apify-docs-theme/static/img/apify_sdk_white.svg
  apify-docs-theme/static/img/favicon.ico
  apify-docs-theme/static/img/favicon.svg
  apify-docs-theme/static/img/footer-apify-logo-black.svg
  apify-docs-theme/static/img/footer-apify-logo-white.svg
  apify-docs-theme/static/img/footer-apify-logo.svg
  apify-docs-theme/static/img/logo-blur.png
  static/img/landing-pages/api.svg
  static/img/landing-pages/api_dark.svg
  static/img/landing-pages/cli.svg
  static/img/landing-pages/cli_dark.svg
  static/img/landing-pages/sdk.svg
  static/img/landing-pages/sdk_dark.svg
Labels: t-web

#1719 chore: bring `logo-blur.png` back [internal]
  apify-docs-theme/static/img/logo-blur.png
Labels: bug, adhoc, t-web

#1724 feat: Update MCP image with a new logo
  sources/platform/images/apify_mcp_server.png
  sources/platform/integrations/ai/mastra.md
  sources/platform/integrations/ai/mcp.md
  sources/platform/integrations/index.mdx
  sources/platform/integrations/integrate_with_apify.md
  static/img/platform/integrations/langflow.png
  static/img/platform/integrations/lindy.png
  static/img/platform/integrations/mcp-logo-white.png
  static/img/platform/integrations/mcp-logo.png
Labels: t-ai

#1708 docs: add note on vulnerability disclosure policy rewards
  sources/platform/security.md
Labels: documentation, adhoc, t-console, security related

#1653 feat: update the course intro and all lesson intros of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_javascript2/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_javascript2/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_javascript2/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
  sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
  sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
  sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
  sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
  sources/academy/webscraping/scraping_basics_javascript2/index.md
Labels: t-academy

#1700 docs: standby incoming requests rate limit
  sources/platform/actors/running/actor_standby.md
Labels: t-ai

#1729 docs: change security description within API docs
  apify-api/openapi/components/securitySchemes/apiKey.yaml
  apify-api/openapi/components/securitySchemes/apiKeyActorBuilds.yaml
  apify-api/openapi/components/securitySchemes/apiKeyQueueId.yaml
  apify-api/openapi/components/securitySchemes/apiKeyStoreId.yaml
  apify-api/openapi/components/securitySchemes/httpBearer.yaml
  apify-api/openapi/components/securitySchemes/httpBearerActorBuilds.yaml
  apify-api/openapi/components/securitySchemes/httpBearerQueueId.yaml
  apify-api/openapi/components/securitySchemes/httpBearerStoreId.yaml
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}.yaml
  apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@openapi.json.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}.yaml
  apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}@openapi.json.yaml
  apify-api/openapi/paths/datasets/datasets@{datasetId}@items.yaml
  apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}.yaml
  apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@keys.yaml
  apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@records@{recordKey}.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}.yaml
  apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}.yaml
Labels: documentation, adhoc, t-docs

#1655 feat: update the DevTools 2 lesson of the JS2 course to be about JavaScript
  sources/academy/webscraping/scraping_basics_javascript2/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
Labels: t-academy

#1732 docs: new impressum page
  sources/legal/index.mdx
Labels: t-docs

#1715 docs: update link to the `EditThisCookie` extension
  sources/academy/glossary/tools/edit_this_cookie.md
Labels: adhoc, t-tooling

#1735 docs: impressum update
  sources/legal/index.mdx
Labels: t-docs
