Repository apify/apify-docs, pull requests merged in 2025-04, with the labels that each got.

#1506 feat: adjust Airtable integration docs
  sources/platform/integrations/data-storage/airtable.md
  sources/platform/integrations/images/airtable/set-up-integration-2.png
Labels: adhoc, t-console

#1517 chore: use `@apify/ui-components` package from NPM
  .github/workflows/docs.yaml
  .github/workflows/lychee.yml
  .github/workflows/openapi.yaml
  .github/workflows/publish-theme.yaml
  .github/workflows/test.yaml
  .npmrc
  CONTRIBUTING.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/ActionCard/ActionCard.tsx
  src/components/ActorTemplates/ActorTemplates.tsx
  src/components/Button.tsx
  src/components/CardWithIcon/CardWithIcon.tsx
  src/components/Heading.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/PlainCard/PlainCard.tsx
  src/components/SdkSection/SdkSection.tsx
  src/components/Section/Section.tsx
  src/components/Tabs.tsx
  src/components/Text.tsx
  src/components/UiLibraryWrapper.tsx
  src/pages/api/index.tsx
  src/pages/index.tsx
  src/pages/open-source/index.tsx
  src/pages/sdk/index.tsx
Labels: adhoc, t-tooling

#1520 docs: remove outdated info
  sources/platform/actors/development/actor_definition/input_schema/specification.md
Labels: documentation, adhoc, t-docs

#1130 feat: updated open source page copy
  src/pages/open-source/index.tsx
Labels: t-docs

#1522 chore: update to latest eslint v9 config
  apify-docs-theme/src/theme/ColorModeToggle/index.jsx
  apify-docs-theme/src/theme/Navbar/Content/index.jsx
  eslint.config.mjs
  package-lock.json
  package.json
  patches/docusaurus-plugin-openapi-docs+4.3.7.patch
  patches/docusaurus-theme-openapi-docs+4.3.7.patch
  src/components/ActionCard/ActionCard.tsx
  src/components/ActorTemplates/ActorTemplates.tsx
  src/components/CardWithIcon/CardWithIcon.tsx
  src/components/ChangeLog/ChangeLog.tsx
  src/components/Hero/Hero.tsx
  src/components/OpenSourceCards/OpenSourceCards.tsx
  src/components/PlainCard/PlainCard.tsx
  src/components/Section/Section.tsx
  src/pages/api/index.tsx
Labels: adhoc, t-tooling

#1510 docs: add missing actor-tasks endpoint
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs@last.yaml
Labels: documentation, adhoc, t-docs

#1519 docs: add new getting started to API docs
  .gitignore
  sources/api/getting-started.mdx
  sources/api/sidebars.js
Labels: documentation, adhoc, t-docs

#1536 fix: Transition length
  apify-docs-theme/src/theme/custom.css
Labels: adhoc, t-web

#1534 docs: whistleblowing and referrals
  sources/legal/latest/policies/whistleblowing-policy.md
  sources/legal/latest/terms/candidate-referral-program-terms-and-conditions.md
Labels: t-docs

#1535 docs: add standby request timeout info
  sources/platform/actors/development/programming_interface/actor_standby.md
  sources/platform/actors/running/actor_standby.md
Labels: adhoc, t-platform

#1542 docs: fix error in cotributing.md
  CONTRIBUTING.md
  repomix-output.xml
Labels: documentation, adhoc, t-docs

#1544 docs: update API docs
  apify-api/openapi/openapi.yaml
  apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@keys.yaml
Labels: documentation, adhoc, t-docs

#1546 docs: add mcp integration doc
  sources/platform/integrations/ai/mcp.md
Labels: documentation, t-docs

#1551 feat: rename the JS course
  .github/styles/config/vocabularies/Docs/accept.txt
  sources/academy/homepage_content.json
  sources/academy/platform/expert_scraping_with_apify/actors_webhooks.md
  sources/academy/platform/expert_scraping_with_apify/index.md
  sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
  sources/academy/webscraping/advanced_web_scraping/index.md
  sources/academy/webscraping/anti_scraping/mitigation/using_proxies.md
  sources/academy/webscraping/puppeteer_playwright/index.md
  sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
  sources/academy/webscraping/scraping_basics_javascript/challenge/modularity.md
  sources/academy/webscraping/scraping_basics_javascript/challenge/scraping_amazon.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/exporting_data.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/index.md
  sources/academy/webscraping/scraping_basics_javascript/crawling/recap_extraction_basics.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/node_continued.md
  sources/academy/webscraping/scraping_basics_javascript/data_extraction/save_to_csv.md
  sources/academy/webscraping/scraping_basics_javascript/index.md
  sources/academy/webscraping/typescript/enums.md
Labels: t-academy

#1543 docs: update publish.mdx
  sources/platform/actors/publishing/publish.mdx
Labels: adhoc, t-c&c

#1557 chore: infer 'sidebar_position' from the filename
  sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/03_devtools_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/08_saving_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/10_crawling.md
  sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
  sources/academy/webscraping/scraping_basics_python/12_framework.md
  sources/academy/webscraping/scraping_basics_python/13_platform.md
Labels: t-academy

#1558 fix: various improvements to the Python course (consistency etc.)
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/03_devtools_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
  sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
  sources/academy/webscraping/scraping_basics_python/09_getting_links.md
  sources/academy/webscraping/scraping_basics_python/images/devtools-product-title.png
  sources/academy/webscraping/scraping_basics_python/index.md
Labels: t-academy

#1559 feat: improve two images in the Python course
  sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
  sources/academy/webscraping/scraping_basics_python/images/devtools-queryselector.png
  sources/academy/webscraping/scraping_basics_python/images/devtools-queryselector.webp
  sources/academy/webscraping/scraping_basics_python/images/scraping.png
  sources/academy/webscraping/scraping_basics_python/images/scraping.webp
  sources/academy/webscraping/scraping_basics_python/index.md
Labels: t-academy
